/**
 * 用户评价 Mock 数据
 * 覆盖 scenic / food / trip 三种类型，内容真实感强
 * 共 20 条评价，覆盖汕头、成都、长沙、西安、厦门、杭州、重庆等多个城市
 */
import type { Review } from '@/types'

export const mockReviews: Review[] = [
  // ---- 景点评价 ----
  {
    id: 'review-1',
    targetType: 'scenic',
    targetId: 'scenic-1',
    targetName: '南澳岛',
    userId: 'user-1',
    userName: '海风旅人',
    rating: 5,
    content: '南澳岛真的太美了！环岛公路一路风景如画，青澳湾的沙滩细腻干净，海水清澈见底。日落时分在灯塔旁拍照，随手一拍就是大片。建议租一辆电动车环岛，慢慢逛，每个海湾都值得停下来。岛上物价也很亲民，海鲜大排档新鲜又便宜。',
    tags: ['值得推荐', '风景绝美', '适合拍照'],
    likes: 42,
    liked: false,
    createdAt: '2025-12-15T10:30:00Z',
  },
  {
    id: 'review-2',
    targetType: 'scenic',
    targetId: 'scenic-2',
    targetName: '汕头小公园',
    userId: 'user-2',
    userName: '城市漫步者',
    rating: 4,
    content: '骑楼建筑群很有民国风情，修缮后焕然一新。老妈宫粽球和飘香小吃都在附近，边逛边吃很惬意。不过节假日人太多了，拍照要找角度避开人群。建议工作日去，体验会好很多。晚上灯光亮起来后更有氛围感。',
    tags: ['文化底蕴', '美食集中'],
    likes: 28,
    liked: true,
    createdAt: '2025-12-20T14:20:00Z',
  },
  {
    id: 'review-3',
    targetType: 'scenic',
    targetId: 'scenic-1',
    targetName: '南澳岛',
    userId: 'user-3',
    userName: '背包客小陈',
    rating: 4,
    content: '整体体验不错，但旺季住宿比较紧张，建议提前预订。风很大，记得带件外套。青澳湾适合游泳，后宅湾更适合看日出。岛上交通不太方便，没有公交，要么租车要么包车。海鲜推荐去后宅镇上的大排档，比景区的实惠很多。',
    tags: ['值得推荐', '注意防风'],
    likes: 15,
    liked: false,
    createdAt: '2026-01-05T09:15:00Z',
  },

  // ---- 美食评价（汕头） ----
  {
    id: 'review-4',
    targetType: 'food',
    targetId: 'food-1',
    targetName: '牛肉火锅',
    userId: 'user-4',
    userName: '吃货阿杰',
    rating: 5,
    content: '牛肉火锅真的绝了，吊龙入口即化，胸口油脆脆的很有嚼劲，匙柄嫩滑多汁。汤底就是清水加萝卜玉米，完全靠牛肉本身的鲜味。涮的时候师傅会教你每个部位烫几秒，这种仪式感太棒了。人均80左右，性价比超高。强烈推荐吊龙和五花趾！',
    tags: ['值得推荐', '味道惊艳', '性价比高'],
    likes: 67,
    liked: false,
    createdAt: '2025-12-18T20:45:00Z',
  },
  {
    id: 'review-5',
    targetType: 'food',
    targetId: 'food-2',
    targetName: '蚝烙',
    userId: 'user-5',
    userName: '小吃达人',
    rating: 4,
    content: '老妈宫的蚝烙确实名不虚传，外皮酥脆，里面的蚝肉肥美多汁。鱼露的味道很特别，第一次吃可能不太习惯，但配上芫荽就很香。25块钱一份分量很足，两个人吃刚好。建议趁热吃，凉了就不够酥了。',
    tags: ['值得推荐', '地道小吃'],
    likes: 33,
    liked: true,
    createdAt: '2025-12-22T11:30:00Z',
  },
  {
    id: 'review-6',
    targetType: 'food',
    targetId: 'food-3',
    targetName: '夜粥（打冷）',
    userId: 'user-6',
    userName: '深夜觅食者',
    rating: 5,
    content: '打冷绝对是汕头美食的灵魂！上百种冷盘随便挑，卤鹅软烂入味，生腌虾鲜甜弹牙，鱼饭肉质紧实。人均40块就能吃到撑，而且都是新鲜现做的。环境虽然一般，但这就是街头美食的魅力啊。晚上10点后才开始营业，真正的深夜食堂。每次来汕头都要来吃一次。',
    tags: ['值得推荐', '性价比高', '深夜美食'],
    likes: 51,
    liked: false,
    createdAt: '2026-01-02T23:10:00Z',
  },
  {
    id: 'review-7',
    targetType: 'food',
    targetId: 'food-4',
    targetName: '老妈宫粽球',
    userId: 'user-7',
    userName: '早餐爱好者',
    rating: 4,
    content: '甜咸双拼的粽球真的很有创意，一半甜一半咸，一口下去两种味道在嘴里融合。豆沙细腻，五花肉入味，栗子粉糯。15块钱一个分量很足，当早餐吃完全够了。不过建议早点去，下午去经常卖完了。',
    tags: ['值得推荐', '早餐首选', '限量供应'],
    likes: 22,
    liked: false,
    createdAt: '2026-01-08T08:00:00Z',
  },

  // ---- 行程评价 ----
  {
    id: 'review-8',
    targetType: 'trip',
    targetId: 'trip-1',
    targetName: '汕头3日美食之旅',
    userId: 'user-8',
    userName: '旅行规划师',
    rating: 5,
    content: '这个行程安排得太合理了！Day1逛老城区吃小吃，Day2南澳岛环岛，Day3牛肉火锅+特产采购。节奏不紧不慢，每天都能吃到当地特色美食。住宿推荐选在金平区，去哪里都方便。预算控制得很好，3天人均不到1500。强烈推荐给第一次来汕头的朋友！',
    tags: ['值得推荐', '安排合理', '预算友好'],
    likes: 38,
    liked: false,
    createdAt: '2026-01-10T16:30:00Z',
  },
  {
    id: 'review-9',
    targetType: 'trip',
    targetId: 'trip-1',
    targetName: '汕头3日美食之旅',
    userId: 'user-9',
    userName: '周末出游党',
    rating: 4,
    content: '整体行程不错，但Day2南澳岛那天稍微有点赶，建议多留半天时间。跨海大桥收费有点贵，来回100多。岛上租电动车要带驾照，我们没带只能包车，多花了不少钱。不过风景确实很美，美食也都没踩雷。下次来会调整一下节奏，慢慢玩。',
    tags: ['值得推荐', '注意交通'],
    likes: 19,
    liked: true,
    createdAt: '2026-01-12T21:00:00Z',
  },
  {
    id: 'review-10',
    targetType: 'trip',
    targetId: 'trip-2',
    targetName: '潮州文化深度游',
    userId: 'user-10',
    userName: '历史迷小李',
    rating: 5,
    content: '潮州古城真的太有味道了！广济桥的"十八梭船廿四洲"设计绝妙，每天傍晚浮桥断开通航的仪式感满满。牌坊街虽然商业化了一些，但古建筑保存得很好。开元寺很安静，适合慢慢逛。潮州菜比汕头菜更精致，卤鹅和春饼必吃。强烈推荐住一晚古城里的民宿，清晨的古城最美。',
    tags: ['值得推荐', '文化底蕴', '适合慢游'],
    likes: 45,
    liked: false,
    createdAt: '2026-01-15T13:45:00Z',
  },

  // ---- 成都美食评价（3条） ----
  {
    id: 'review-11',
    targetType: 'food',
    targetId: 'food-5',
    targetName: '串串香',
    userId: 'user-11',
    userName: '成都吃货王',
    rating: 5,
    content: '马路边边的串串香真的太有氛围了！坐在小马扎上，围着铁锅涮串串，瞬间穿越回80年代的成都。麻辣牛肉是必点的，辣得过瘾又停不下来。鲜毛肚七上八下涮几秒就吃，脆嫩爽口。最后一定要来一碗冰粉解辣，红糖冰粉配上山楂碎和葡萄干，完美收尾。人均60块，吃到扶墙出！',
    tags: ['值得推荐', '氛围感满分', '性价比高'],
    likes: 56,
    liked: false,
    createdAt: '2026-01-20T21:30:00Z',
  },
  {
    id: 'review-12',
    targetType: 'food',
    targetId: 'food-6',
    targetName: '担担面',
    userId: 'user-12',
    userName: '面食爱好者',
    rating: 4,
    content: '洞子口张老二的担担面果然名不虚传！面条筋道，臊子炒得喷香，红油辣而不燥。最惊喜的是甜水面，又粗又硬的面条裹满红糖辣酱，甜辣交织的口感太独特了。钟水饺也推荐，皮薄馅大，红油味正。20块钱就能吃到三样经典小吃，成都的物价太感人了。建议工作日去，周末排队很久。',
    tags: ['值得推荐', '地道老店', '价格实惠'],
    likes: 34,
    liked: true,
    createdAt: '2026-02-01T12:15:00Z',
  },
  {
    id: 'review-13',
    targetType: 'food',
    targetId: 'food-8',
    targetName: '冒菜',
    userId: 'user-13',
    userName: '一个人的旅行',
    rating: 5,
    content: '三顾冒菜真的是"一个人的火锅"天花板！冒牛肉大片厚实，入口麻辣鲜香；冒千层肚脆嫩弹牙，裹满红油蒜泥。配上一碗白米饭，把红油汤汁拌进饭里，简直是人间美味。玉林路这家店开了很多年，底料配方一直没变，每次来成都都要来吃。35块钱一份冒菜加米饭，管饱又管好。',
    tags: ['值得推荐', '一个人也能吃好', '味道正宗'],
    likes: 41,
    liked: false,
    createdAt: '2026-02-10T19:00:00Z',
  },

  // ---- 西安景点评价（2条） ----
  {
    id: 'review-14',
    targetType: 'scenic',
    targetId: 'scenic-xian-1',
    targetName: '秦始皇兵马俑',
    userId: 'user-14',
    userName: '历史控小张',
    rating: 5,
    content: '亲眼看到兵马俑的那一刻真的被震撼到了！一号坑的规模太大了，几千个兵俑排列整齐，每个面部表情都不一样，两千多年前的工艺简直不可思议。强烈建议请讲解员，不然就是看一堆泥人。二号坑的跪射俑和骑兵阵也很精彩，铜车马展厅的铜车工艺更是精美绝伦。门票120元绝对值回票价。',
    tags: ['值得推荐', '震撼人心', '必请讲解'],
    likes: 73,
    liked: false,
    createdAt: '2026-02-15T14:00:00Z',
  },
  {
    id: 'review-15',
    targetType: 'scenic',
    targetId: 'scenic-xian-4',
    targetName: '大唐不夜城',
    userId: 'user-15',
    userName: '夜游达人',
    rating: 4,
    content: '大唐不夜城的夜景真的太美了！整条街灯火辉煌，仿佛穿越回了盛唐长安。不倒翁小姐姐的表演很精彩，互动感很强，但排队拍照要等很久。花车巡游和诗词互动区也很有意思。最关键的是免费开放！建议晚上7点以后去，灯光全开最漂亮。周边的餐厅价格偏贵，建议吃饱了再来逛。',
    tags: ['值得推荐', '夜景绝美', '免费开放'],
    likes: 48,
    liked: true,
    createdAt: '2026-02-20T20:30:00Z',
  },

  // ---- 厦门评价（2条） ----
  {
    id: 'review-16',
    targetType: 'scenic',
    targetId: 'scenic-xm-1',
    targetName: '鼓浪屿',
    userId: 'user-16',
    userName: '文艺小清新',
    rating: 4,
    content: '鼓浪屿真的很适合慢慢逛！日光岩登顶后可以俯瞰全岛和厦门市区，视野超棒。万国建筑群很有异域风情，每栋别墅都有故事。龙头路的小吃很多，张三疯奶茶和赵小姐的店是必打卡的。不过周末人真的太多了，建议工作日来。船票一定要提前在微信上预约，现场买票经常没位。',
    tags: ['值得推荐', '适合慢游', '注意预约船票'],
    likes: 37,
    liked: false,
    createdAt: '2026-03-01T16:00:00Z',
  },
  {
    id: 'review-17',
    targetType: 'food',
    targetId: 'food-xm-1',
    targetName: '沙茶面',
    userId: 'user-17',
    userName: '面食猎人',
    rating: 5,
    content: '厦门的沙茶面真的太好吃了！汤底用沙茶酱、花生、虾米等十几种材料熬制，浓郁鲜香，微甜微辣。面条用的是碱面，口感爽滑。配料可以自己选，豆腐、猪肝、大肠、虾仁都很新鲜。乌糖沙茶面是本地人最推荐的老店，虽然店面很小但味道正宗。人均20块就能吃到一碗满满当当的沙茶面，厦门美食性价比之王！',
    tags: ['值得推荐', '味道惊艳', '本地人推荐'],
    likes: 29,
    liked: false,
    createdAt: '2026-03-05T11:30:00Z',
  },

  // ---- 杭州评价（2条） ----
  {
    id: 'review-18',
    targetType: 'scenic',
    targetId: 'scenic-hz-1',
    targetName: '西湖',
    userId: 'user-18',
    userName: '江南客',
    rating: 5,
    content: '西湖真的不愧是人间天堂！断桥残雪虽然没赶上雪景，但春天的断桥桃红柳绿也很美。白堤漫步特别舒服，两边都是桃花和垂柳。强烈推荐坐手摇船游湖，船夫会讲西湖的传说故事，150元一小时很值。雷峰塔登上去可以看西湖全景，傍晚去还能看日落。西湖完全免费，杭州对游客太友好了。',
    tags: ['值得推荐', '免费景点', '四季皆美'],
    likes: 62,
    liked: true,
    createdAt: '2026-03-10T15:00:00Z',
  },
  {
    id: 'review-19',
    targetType: 'food',
    targetId: 'food-hz-1',
    targetName: '片儿川',
    userId: 'user-19',
    userName: '杭州土著',
    rating: 4,
    content: '奎元馆的片儿川是杭州人的骄傲！面条是手工现擀的，又宽又薄，口感滑嫩。浇头是笋片、雪菜和瘦肉，笋片脆嫩鲜甜，雪菜咸香开胃，汤底清澈鲜美。一碗片儿川15块钱，在景区附近算很良心了。建议加一份爆鳝，鳝鱼段炸得外酥里嫩，拌进面里绝了。百年老店的味道确实不一样。',
    tags: ['值得推荐', '百年老店', '杭州必吃'],
    likes: 25,
    liked: false,
    createdAt: '2026-03-15T12:00:00Z',
  },

  // ---- 重庆评价（1条） ----
  {
    id: 'review-20',
    targetType: 'scenic',
    targetId: 'scenic-cq-1',
    targetName: '洪崖洞',
    userId: 'user-20',
    userName: '山城探险家',
    rating: 4,
    content: '洪崖洞的夜景真的像千与千寻里的场景！从千厮门大桥上拍全景最出片，灯火辉煌的吊脚楼层层叠叠，倒映在嘉陵江面上，太梦幻了。不过里面人真的超级多，尤其是周末晚上，几乎是摩肩接踵。建议从11楼的城市阳台进入，一层一层往下逛，最后到嘉陵江边。洞子火锅体验很独特，在防空洞里吃火锅，重庆人太会利用地形了。',
    tags: ['值得推荐', '夜景绝美', '人多注意安全'],
    likes: 44,
    liked: false,
    createdAt: '2026-03-20T22:00:00Z',
  },
]
