/**
 * 目的地推荐 Mock 数据
 * 包含 12 个国内热门目的地，每个目的地有完整的评分和标签信息
 * 数据经过真实性校验，评分、预算、季节均参考真实水平
 */
import type { Destination } from '@/types'

export const mockDestinations: Destination[] = [
  {
    id: 'chengdu',
    name: '成都',
    province: '四川',
    coverImage: 'linear-gradient(135deg, #FF6B35, #FFD166)',
    description: '天府之国，一座来了就不想走的城市。这里有悠闲的茶馆文化、热辣的川菜美食、可爱的大熊猫，以及深厚的巴蜀文化底蕴。',
    tags: ['food', 'culture', 'family'],
    bestSeason: '3-6月 / 9-11月',
    avgBudget: 320,
    avgDays: 4,
    rating: 4.7,
    highlights: ['大熊猫繁育研究基地', '宽窄巷子', '锦里古街', '都江堰', '川剧变脸'],
    foodScore: 4.9,
    scenicScore: 4.3,
    cultureScore: 4.6,
    transportScore: 4.5,
    costScore: 4.7,
  },
  {
    id: 'hangzhou',
    name: '杭州',
    province: '浙江',
    coverImage: 'linear-gradient(135deg, #06D6A0, #4ECDC4)',
    description: '人间天堂，西湖美景四季皆宜。龙井茶香弥漫山间，宋韵文化流淌千年，是诗意与自然的完美融合。',
    tags: ['nature', 'culture', 'romantic'],
    bestSeason: '3-5月 / 9-11月',
    avgBudget: 380,
    avgDays: 3,
    rating: 4.6,
    highlights: ['西湖十景', '灵隐寺', '龙井茶园', '西溪湿地', '河坊街'],
    foodScore: 4.3,
    scenicScore: 4.8,
    cultureScore: 4.7,
    transportScore: 4.6,
    costScore: 4.0,
  },
  {
    id: 'dali',
    name: '大理',
    province: '云南',
    coverImage: 'linear-gradient(135deg, #8B5CF6, #EC4899)',
    description: '风花雪月之城，苍山洱海相依相伴。白族古镇韵味悠长，是文艺青年和慢生活爱好者的理想之地。',
    tags: ['nature', 'romantic', 'budget'],
    bestSeason: '3-5月',
    avgBudget: 250,
    avgDays: 4,
    rating: 4.5,
    highlights: ['洱海环湖', '大理古城', '苍山索道', '双廊古镇', '崇圣寺三塔'],
    foodScore: 4.2,
    scenicScore: 4.9,
    cultureScore: 4.4,
    transportScore: 3.8,
    costScore: 4.8,
  },
  {
    id: 'xian',
    name: '西安',
    province: '陕西',
    coverImage: 'linear-gradient(135deg, #F59E0B, #EF476F)',
    description: '十三朝古都，千年历史沉淀。兵马俑震撼世界，古城墙诉说沧桑，回民街美食飘香四溢，大唐不夜城重现盛唐气象。',
    tags: ['culture', 'food', 'family'],
    bestSeason: '3-5月 / 9-11月',
    avgBudget: 300,
    avgDays: 4,
    rating: 4.6,
    highlights: ['秦始皇兵马俑', '古城墙骑行', '回民街', '大唐不夜城', '华清宫'],
    foodScore: 4.6,
    scenicScore: 4.5,
    cultureScore: 5.0,
    transportScore: 4.4,
    costScore: 4.5,
  },
  {
    id: 'xiamen',
    name: '厦门',
    province: '福建',
    coverImage: 'linear-gradient(135deg, #4ECDC4, #44CF6C)',
    description: '海上花园，文艺小资的天堂。鼓浪屿的琴声悠扬，曾厝垵的烟火气十足，环岛路的海风沁人心脾。',
    tags: ['romantic', 'food', 'nature'],
    bestSeason: '3-5月 / 10-12月',
    avgBudget: 350,
    avgDays: 3,
    rating: 4.5,
    highlights: ['鼓浪屿', '南普陀寺', '曾厝垵', '环岛路', '沙坡尾'],
    foodScore: 4.5,
    scenicScore: 4.6,
    cultureScore: 4.2,
    transportScore: 4.3,
    costScore: 4.0,
  },
  {
    id: 'changsha',
    name: '长沙',
    province: '湖南',
    coverImage: 'linear-gradient(135deg, #EF476F, #FF6B35)',
    description: '网红美食之都，夜生活丰富多彩。茶颜悦色、臭豆腐、小龙虾，还有橘子洲头的壮阔湘江，是一座让人来了就不想走的城市。',
    tags: ['food', 'culture', 'budget'],
    bestSeason: '4-6月 / 9-11月',
    avgBudget: 280,
    avgDays: 3,
    rating: 4.4,
    highlights: ['橘子洲头', '岳麓山', '太平老街', '茶颜悦色', '湖南省博物馆'],
    foodScore: 4.8,
    scenicScore: 4.2,
    cultureScore: 4.3,
    transportScore: 4.5,
    costScore: 4.9,
  },
  {
    id: 'chongqing',
    name: '重庆',
    province: '重庆',
    coverImage: 'linear-gradient(135deg, #FF3D00, #FF9100)',
    description: '8D 魔幻城市，山城夜景璀璨夺目。火锅之都麻辣鲜香，洪崖洞的灯火如梦似幻，轻轨穿楼令人惊叹。',
    tags: ['food', 'adventure', 'culture'],
    bestSeason: '3-5月 / 9-11月',
    avgBudget: 280,
    avgDays: 4,
    rating: 4.6,
    highlights: ['洪崖洞', '长江索道', '磁器口古镇', '解放碑', '穿楼轻轨'],
    foodScore: 4.9,
    scenicScore: 4.4,
    cultureScore: 4.3,
    transportScore: 4.0,
    costScore: 4.6,
  },
  {
    id: 'lijiang',
    name: '丽江',
    province: '云南',
    coverImage: 'linear-gradient(135deg, #7C3AED, #2563EB)',
    description: '雪山脚下的浪漫古城，纳西文化神秘悠远。玉龙雪山巍峨壮丽，古城小桥流水别有风情。',
    tags: ['romantic', 'nature', 'culture'],
    bestSeason: '4-5月 / 9-10月',
    avgBudget: 350,
    avgDays: 4,
    rating: 4.4,
    highlights: ['玉龙雪山', '丽江古城', '束河古镇', '蓝月谷', '泸沽湖'],
    foodScore: 4.0,
    scenicScore: 4.8,
    cultureScore: 4.5,
    transportScore: 3.5,
    costScore: 3.8,
  },
  {
    id: 'guilin',
    name: '桂林',
    province: '广西',
    coverImage: 'linear-gradient(135deg, #10B981, #06B6D4)',
    description: '山水甲天下，漓江如诗如画。喀斯特地貌鬼斧神工，阳朔西街热闹非凡，龙脊梯田气势磅礴。',
    tags: ['nature', 'adventure', 'family'],
    bestSeason: '4-10月',
    avgBudget: 300,
    avgDays: 4,
    rating: 4.5,
    highlights: ['漓江竹筏', '阳朔西街', '龙脊梯田', '象鼻山', '遇龙河漂流'],
    foodScore: 4.1,
    scenicScore: 5.0,
    cultureScore: 3.8,
    transportScore: 3.9,
    costScore: 4.4,
  },
  {
    id: 'qingdao',
    name: '青岛',
    province: '山东',
    coverImage: 'linear-gradient(135deg, #0EA5E9, #06D6A0)',
    description: '红瓦绿树，碧海蓝天。啤酒飘香的城市，欧式建筑点缀海岸线，是夏日避暑的绝佳选择。',
    tags: ['nature', 'family', 'food'],
    bestSeason: '6-9月',
    avgBudget: 320,
    avgDays: 3,
    rating: 4.4,
    highlights: ['栈桥', '八大关', '崂山', '青岛啤酒博物馆', '金沙滩'],
    foodScore: 4.3,
    scenicScore: 4.5,
    cultureScore: 4.0,
    transportScore: 4.4,
    costScore: 4.3,
  },
  {
    id: 'suzhou',
    name: '苏州',
    province: '江苏',
    coverImage: 'linear-gradient(135deg, #EC4899, #F59E0B)',
    description: '上有天堂，下有苏杭。精致园林甲天下，昆曲评弹余音绕梁，是江南水乡的极致代表。',
    tags: ['culture', 'romantic', 'luxury'],
    bestSeason: '3-5月 / 9-11月',
    avgBudget: 400,
    avgDays: 3,
    rating: 4.5,
    highlights: ['拙政园', '虎丘', '平江路', '周庄古镇', '苏州博物馆'],
    foodScore: 4.2,
    scenicScore: 4.6,
    cultureScore: 4.9,
    transportScore: 4.7,
    costScore: 3.9,
  },
  {
    id: 'beijing',
    name: '北京',
    province: '北京',
    coverImage: 'linear-gradient(135deg, #DC2626, #F59E0B)',
    description: '千年帝都，现代与传统的完美交融。故宫的恢弘、长城的壮丽、胡同的烟火气，每一处都是中国故事。',
    tags: ['culture', 'family', 'luxury'],
    bestSeason: '4-5月 / 9-10月',
    avgBudget: 500,
    avgDays: 5,
    rating: 4.7,
    highlights: ['故宫博物院', '万里长城（八达岭）', '颐和园', '天坛公园', '南锣鼓巷'],
    foodScore: 4.4,
    scenicScore: 4.7,
    cultureScore: 5.0,
    transportScore: 4.8,
    costScore: 3.5,
  },
  {
    id: 'sanya',
    name: '三亚',
    province: '海南',
    coverImage: 'linear-gradient(135deg, #0EA5E9, #22D3EE)',
    description: '东方夏威夷，碧海蓝天白沙滩。热带风情浓郁，是国内最热门的海滨度假胜地，适合亲子游和情侣度假。',
    tags: ['nature', 'romantic', 'family'],
    bestSeason: '10月-次年3月',
    avgBudget: 450,
    avgDays: 4,
    rating: 4.5,
    highlights: ['亚龙湾', '天涯海角', '蜈支洲岛', '南山文化旅游区', '呀诺达雨林'],
    foodScore: 4.3,
    scenicScore: 4.9,
    cultureScore: 3.5,
    transportScore: 3.8,
    costScore: 3.2,
  },
]
