/**
 * 景点多方案规划 - Mock 数据
 * 覆盖汕头、成都、西安、厦门、杭州、重庆 6 个城市
 * 每个城市 1 个景点，每个景点 4 种游览方案
 */

/** 方案类型 */
export type ScenicPlanType = 'mainstream' | 'economy' | 'deep' | 'special'

/** 景点游览方案 */
export interface ScenicPlan {
  /** 方案名称（如"主流游览方案"） */
  planName: string
  /** 方案类型 */
  planType: ScenicPlanType
  /** 预计时长（如"3-4小时"） */
  duration: string
  /** 预计花费 */
  cost: number
  /** 方案描述 */
  description: string
  /** 亮点列表 */
  highlights: string[]
  /** 实用贴士 */
  tips: string[]
}

/** 景点方案数据 */
export interface ScenicPlanData {
  /** 景点名称 */
  scenicName: string
  /** 所属城市 */
  city?: string
  /** 该景点的所有游览方案 */
  plans: ScenicPlan[]
}

/** 方案类型配置映射 */
export const planTypeConfig: Record<ScenicPlanType, { label: string; color: string; bgColor: string }> = {
  mainstream: {
    label: '主流',
    color: 'text-blue-700 dark:text-blue-400',
    bgColor: 'bg-blue-100 dark:bg-blue-900/30',
  },
  economy: {
    label: '经济',
    color: 'text-green-700 dark:text-green-400',
    bgColor: 'bg-green-100 dark:bg-green-900/30',
  },
  deep: {
    label: '深度',
    color: 'text-purple-700 dark:text-purple-400',
    bgColor: 'bg-purple-100 dark:bg-purple-900/30',
  },
  special: {
    label: '特殊',
    color: 'text-amber-700 dark:text-amber-400',
    bgColor: 'bg-amber-100 dark:bg-amber-900/30',
  },
}

/** Mock 景点方案数据 */
export const mockScenicPlans: ScenicPlanData[] = [
  // ============ 汕头 ============
  {
    scenicName: '南澳岛',
    city: '汕头',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '4-5小时',
        cost: 200,
        description: '经典南澳岛一日游路线，覆盖主要景点，适合第一次来的游客。',
        highlights: ['南澳大桥观景', '青澳湾沙滩漫步', '总兵府参观', '风电场观景台拍照', '海鲜大排档午餐'],
        tips: ['建议自驾或包车', '防晒必备', '带上泳衣可以下水', '周末人多建议早出发'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '3-4小时',
        cost: 80,
        description: '用最少的钱体验南澳岛的魅力，公共交通可达。',
        highlights: ['公交车上岛', '青澳湾免费沙滩', '渔民码头看日落', '路边摊吃海鲜'],
        tips: ['公交班次少，注意末班车时间', '自带水和零食', '路边摊海鲜注意新鲜度'],
      },
      {
        planName: '深度探索方案',
        planType: 'deep',
        duration: '全天（8-10小时）',
        cost: 350,
        description: '深入探索南澳岛的每一个角落，发现隐藏的美景。',
        highlights: ['南澳大桥日出', '三囱崖灯塔', '后花园湾野生沙滩', '宋井探秘', '黄花山森林公园徒步', '渔排体验（乘船出海）', '青澳湾日落'],
        tips: ['需要自驾', '穿运动鞋', '带足饮用水', '充电宝必备', '部分路段信号弱'],
      },
      {
        planName: '浪漫情侣方案',
        planType: 'special',
        duration: '5-6小时',
        cost: 300,
        description: '专为情侣设计的浪漫海岛之旅，包含多个网红打卡点。',
        highlights: ['南澳大桥情侣合影', '青澳湾沙滩漫步', '网红咖啡厅下午茶', '海边日落晚餐', '星空观测（天气好时）'],
        tips: ['提前预订海边餐厅', '带一件薄外套（海风大）', '日落时间提前查好'],
      },
    ],
  },
  {
    scenicName: '汕头小公园',
    city: '汕头',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '2-3小时',
        cost: 0,
        description: '经典骑楼街区游览路线，打卡必去景点。',
        highlights: ['中山纪念亭拍照', '百货大楼外观', '老妈宫参观', '骑楼街巷漫步', '周边小吃打卡'],
        tips: ['建议下午4-6点去，光线好', '穿舒适的鞋子', '周边有很多小吃可以边走边吃'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '1-2小时',
        cost: 30,
        description: '快速游览核心区域，预算极低。',
        highlights: ['中山纪念亭', '骑楼外观欣赏', '一个蛋挞+一杯奶茶', '免费拍照打卡'],
        tips: ['不需要门票', '自带水', '周末人多注意保管财物'],
      },
      {
        planName: '深度文化方案',
        planType: 'deep',
        duration: '4-5小时',
        cost: 50,
        description: '深入了解汕头开埠历史和骑楼建筑文化。',
        highlights: ['开埠文化陈列馆', '侨批文物馆', '非遗展示馆', '镇邦路骑楼群', '汕头旅社旧址', '老妈宫戏台（周末有潮剧）'],
        tips: ['部分展馆周一闭馆', '建议请个讲解员（50元）', '带笔记本记录有趣的历史故事'],
      },
      {
        planName: '美食探索方案',
        planType: 'special',
        duration: '3-4小时',
        cost: 80,
        description: '以小公园为中心的美食探店路线。',
        highlights: ['老妈宫粽球', '飘香小吃', '广场豆花', '爱西干面', '榕香蚝烙', '十二中草莓冰'],
        tips: ['空腹前往', '每样少吃点留肚子给下一家', '带现金（部分老店不支持扫码）'],
      },
    ],
  },

  // ============ 成都 ============
  {
    scenicName: '宽窄巷子',
    city: '成都',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '2-3小时',
        cost: 0,
        description: '经典游览路线，感受成都慢生活与巴蜀文化，适合初次到访的游客。',
        highlights: ['宽巷子品盖碗茶', '窄巷子逛文创小店', '井巷子看砖文化墙', '掏耳朵体验', '川剧变脸表演'],
        tips: ['免费开放，无需门票', '建议下午2-4点去，可以坐下来喝茶', '掏耳朵价格提前问清楚'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '1-2小时',
        cost: 20,
        description: '低成本体验宽窄巷子的核心魅力，主打"逛吃逛吃"。',
        highlights: ['巷子漫步拍照', '一碗冰粉+一碗凉糕', '盖碗茶最低消费10元', '免费看街头艺人表演'],
        tips: ['自带水杯', '巷子里的小吃比外面贵，可以只看不买', '拍照打卡免费'],
      },
      {
        planName: '深度文化方案',
        planType: 'deep',
        duration: '4-5小时',
        cost: 150,
        description: '深入了解宽窄巷子的历史变迁和川蜀文化精髓。',
        highlights: ['成都画院参观', '川剧变脸专场演出', '蜀绣体验工坊', '宽窄巷子历史讲座', '私房菜馆品正宗川菜', '夜间灯光漫步'],
        tips: ['川剧演出需提前购票', '蜀绣体验需预约', '建议穿汉服拍照效果更佳'],
      },
      {
        planName: '美食探店方案',
        planType: 'special',
        duration: '3-4小时',
        cost: 120,
        description: '以宽窄巷子为中心，探索周边地道成都美食。',
        highlights: ['宽巷子盖碗茶配三大炮', '窄巷子私房火锅', '巷子外的冒椒火辣', '人民公园鹤鸣茶社', '魁星楼街串串香'],
        tips: ['宽窄巷子内餐饮偏贵，建议到周边巷子吃', '魁星楼街步行5分钟，美食密集', '留肚子给火锅'],
      },
    ],
  },
  {
    scenicName: '成都大熊猫繁育研究基地',
    city: '成都',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '3-4小时',
        cost: 55,
        description: '经典游览路线，看大熊猫的最佳选择，覆盖所有主要场馆。',
        highlights: ['太阳产房看熊猫宝宝', '月亮产房看幼年熊猫', '成年大熊猫别墅', '小熊猫活动场', '熊猫科学探秘馆'],
        tips: ['门票55元，建议网上提前预约', '早上7:30开门，8-10点熊猫最活跃', '建议坐观光车（10元）节省体力'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '2-3小时',
        cost: 65,
        description: '控制预算的同时不错过大熊猫的精彩瞬间。',
        highlights: ['步行游览核心区域', '成年大熊猫活动场', '免费科普讲解', '纪念品店逛逛'],
        tips: ['不坐观光车可以省10元', '自带水和零食', '学生票半价27元'],
      },
      {
        planName: '深度体验方案',
        planType: 'deep',
        duration: '全天（6-8小时）',
        cost: 200,
        description: '沉浸式体验熊猫基地的全部魅力，适合熊猫爱好者。',
        highlights: ['7:30入园看早餐喂食', '志愿者讲解（免费）', '大熊猫博物馆', '天鹅湖湿地漫步', '园区全步行深度游览', '熊猫邮局寄明信片'],
        tips: ['一定要早起！熊猫上午活跃下午睡觉', '穿舒适运动鞋', '带望远镜可以看得更清楚'],
      },
      {
        planName: '亲子家庭方案',
        planType: 'special',
        duration: '4-5小时',
        cost: 150,
        description: '专为带小朋友的家庭设计，寓教于乐。',
        highlights: ['熊猫科普课堂', '亲子互动体验区', '熊猫主题游乐设施', '熊猫纪念品DIY', '园区观光车全程'],
        tips: ['租一个儿童推车（20元）', '带防晒霜和驱蚊液', '园区内有餐厅但价格偏贵'],
      },
    ],
  },
  {
    scenicName: '都江堰',
    city: '成都',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '4-5小时',
        cost: 120,
        description: '经典游览路线，了解两千年前李冰父子修建的水利奇迹。',
        highlights: ['鱼嘴分水堤', '飞沙堰泄洪道', '宝瓶口引水口', '安澜索桥', '二王庙'],
        tips: ['门票80元+观光车15元+讲解器20元', '建议请讲解员了解水利工程原理', '穿防滑鞋'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '3-4小时',
        cost: 80,
        description: '步行游览核心景区，深度感受古人智慧。',
        highlights: ['鱼嘴分水堤', '宝瓶口', '安澜索桥', '离堆公园'],
        tips: ['不坐观光车步行即可', '学生票40元', '自带午餐在离堆公园野餐'],
      },
      {
        planName: '深度文化方案',
        planType: 'deep',
        duration: '全天（8小时）',
        cost: 250,
        description: '都江堰+青城山联游，一天领略水利文化与道教名山。',
        highlights: ['都江堰全景区', '青城山前山', '建福宫', '天师洞', '上清宫', '老君阁俯瞰成都平原'],
        tips: ['联票180元更划算', '先游都江堰再上青城山', '青城山索道单程35元'],
      },
      {
        planName: '夜景灯光方案',
        planType: 'special',
        duration: '3-4小时',
        cost: 150,
        description: '傍晚入园，欣赏都江堰夜景灯光秀，别有一番风味。',
        highlights: ['南桥夜景', '都江堰放水仪式（季节性）', '灌县古城夜游', '夜游岷江', '古城区美食'],
        tips: ['夏季有夜间放水仪式', '南桥夜景免费观赏', '灌县古城有很多小吃'],
      },
    ],
  },
  {
    scenicName: '锦里古街',
    city: '成都',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '2-3小时',
        cost: 50,
        description: '感受三国文化与成都民俗的经典路线，紧邻武侯祠。',
        highlights: ['武侯祠参观', '锦里古街漫步', '三国文化体验', '民俗表演', '特色小吃品尝'],
        tips: ['武侯祠门票50元，锦里免费', '建议先逛武侯祠再逛锦里', '下午5点后灯笼亮起最有氛围'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '1-2小时',
        cost: 30,
        description: '免费逛锦里，只看不买也能感受浓郁的文化氛围。',
        highlights: ['锦里古街免费漫步', '街头艺人表演', '建筑拍照打卡', '一碗凉粉+一碗糖油果子'],
        tips: ['锦里免费开放', '小吃可以每样买一份尝尝', '晚上来更有氛围'],
      },
      {
        planName: '深度三国文化方案',
        planType: 'deep',
        duration: '5-6小时',
        cost: 180,
        description: '深度体验三国文化，从武侯祠到锦里，穿越回蜀汉时代。',
        highlights: ['武侯祠深度讲解', '刘备殿', '诸葛亮殿', '锦里皮影戏', '三国主题茶馆', '川剧变脸演出'],
        tips: ['武侯祠讲解器20元', '皮影戏和变脸演出需额外购票', '建议下午来，可以一直逛到晚上'],
      },
      {
        planName: '美食文化方案',
        planType: 'special',
        duration: '3-4小时',
        cost: 100,
        description: '以锦里为中心的成都小吃深度体验。',
        highlights: ['三大炮', '张飞牛肉', '糖油果子', '钵钵鸡', '锦里酒吧街小酌', '手工糖画体验'],
        tips: ['锦里小吃价格略贵但种类齐全', '建议多人分食，每样尝一点', '酒吧街晚上很热闹'],
      },
    ],
  },

  // ============ 西安 ============
  {
    scenicName: '秦始皇兵马俑博物馆',
    city: '西安',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '4-5小时',
        cost: 160,
        description: '经典游览路线，一次看全一号坑、二号坑、三号坑和铜车马展厅。',
        highlights: ['一号坑（最大，震撼）', '二号坑（兵种最全）', '三号坑（指挥部）', '铜车马展厅', '兵马俑文创商店'],
        tips: ['门票120元，建议网上预约', '请讲解员（约100元）否则看不懂', '周一闭馆'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '3-4小时',
        cost: 140,
        description: '只看核心展馆，节省预算的同时不错过精华。',
        highlights: ['一号坑（必看）', '铜车马展厅', '免费语音导览（手机扫码）', '外围拍照'],
        tips: ['学生票60元', '自带午餐', '蹭听其他旅行团的讲解'],
      },
      {
        planName: '深度历史方案',
        planType: 'deep',
        duration: '全天（8小时）',
        cost: 300,
        description: '兵马俑+秦始皇陵+骊山联游，深度了解秦朝历史。',
        highlights: ['兵马俑全馆', '秦始皇陵遗址公园', '骊山风景区', '华清宫（可选）', '临潼博物馆'],
        tips: ['联票更划算', '建议包车或坐旅游专线', '一天时间很紧，建议早起出发'],
      },
      {
        planName: '摄影创作方案',
        planType: 'special',
        duration: '5-6小时',
        cost: 200,
        description: '专为摄影爱好者设计，捕捉兵马俑最震撼的镜头。',
        highlights: ['一号坑全景拍摄', '兵俑面部特写', '铜车马细节', '光影最佳时段', '文创区汉服体验拍照'],
        tips: ['带上长焦镜头', '上午光线最好', '部分区域禁止使用三脚架', '周一闭馆注意避开'],
      },
    ],
  },
  {
    scenicName: '回民街',
    city: '西安',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '2-3小时',
        cost: 80,
        description: '西安最著名的美食街区，品尝正宗回民美食。',
        highlights: ['贾三灌汤包', '老米家羊肉泡馍', '红柳烤肉', '桂花糕', '酸梅汤'],
        tips: ['免费开放', '建议傍晚去，烟火气最浓', '人多拥挤注意随身物品'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '1-2小时',
        cost: 30,
        description: '花最少的钱吃到最经典的西安小吃。',
        highlights: ['肉夹馍（10元）', '凉皮（8元）', '冰峰汽水（3元）', '甑糕（5元）', '柿子饼（5元）'],
        tips: ['避开主街，去旁边的巷子更便宜', '每样买一份尝尝', '带现金部分老店不支持扫码'],
      },
      {
        planName: '深度美食方案',
        planType: 'deep',
        duration: '4-5小时',
        cost: 150,
        description: '从回民街延伸到周边小巷，探索更多隐藏美食。',
        highlights: ['主街打卡', '大皮院深度探索', '洒金桥美食街', '庙后街特色小吃', '化觉巷清真大寺'],
        tips: ['本地人去洒金桥更多', '化觉巷清真大寺值得一看', '留足肚子，每样少吃点'],
      },
      {
        planName: '文化体验方案',
        planType: 'special',
        duration: '3-4小时',
        cost: 100,
        description: '了解回民街的历史文化和伊斯兰建筑。',
        highlights: ['化觉巷清真大寺', '高家大院看皮影戏', '回民街历史讲解', '手工艺品选购', '传统糕点制作体验'],
        tips: ['清真大寺门票25元', '皮影戏演出约50元', '尊重回族文化习俗'],
      },
    ],
  },
  {
    scenicName: '华清宫',
    city: '西安',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '3-4小时',
        cost: 140,
        description: '感受唐代皇家温泉行宫的恢弘与浪漫。',
        highlights: ['华清池遗址', '长生殿', '九龙湖', '五间厅（西安事变旧址）', '唐代御汤遗址'],
        tips: ['门票120元', '建议请讲解员', '和兵马俑在同一条线上，可以一天游览'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '2-3小时',
        cost: 70,
        description: '快速游览核心景点，感受历史氛围。',
        highlights: ['华清池外观', '九龙湖免费区域', '五间厅', '手机扫码听讲解'],
        tips: ['学生票60元', '不进室内展馆可以省部分费用', '自带午餐'],
      },
      {
        planName: '深度历史文化方案',
        planType: 'deep',
        duration: '全天（6-8小时）',
        cost: 350,
        description: '华清宫+骊山+长恨歌演出，全方位体验盛唐文化。',
        highlights: ['华清宫全景区', '骊山索道', '兵谏亭', '烽火台', '长恨歌实景演出（晚）'],
        tips: ['长恨歌演出票需提前预订（约250元）', '骊山索道往返60元', '建议下午来，看完演出再走'],
      },
      {
        planName: '浪漫情侣方案',
        planType: 'special',
        duration: '4-5小时',
        cost: 300,
        description: '以唐玄宗与杨贵妃的爱情故事为主题的文化之旅。',
        highlights: ['长生殿爱情故事展', '海棠汤（贵妃池）', '九龙湖畔漫步', '唐风汉服体验', '长恨歌实景演出'],
        tips: ['可以租汉服拍照（约100元）', '长恨歌演出是重头戏', '建议傍晚入园'],
      },
    ],
  },
  {
    scenicName: '大唐不夜城',
    city: '西安',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '2-3小时',
        cost: 0,
        description: '免费开放的步行街，感受盛唐长安的繁华夜景。',
        highlights: ['大雁塔北广场', '不倒翁小姐姐表演', '诗词互动区', '花车巡游', '盛唐主题灯光秀'],
        tips: ['免费开放', '晚上7-9点最热闹', '地铁4号线大雁塔站直达'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '1-2小时',
        cost: 20,
        description: '零成本感受西安夜景天花板。',
        highlights: ['步行街漫步', '免费表演观看', '灯光拍照', '一碗biangbiang面'],
        tips: ['完全免费', '自带水', '表演时间建议提前查好'],
      },
      {
        planName: '深度唐文化方案',
        planType: 'deep',
        duration: '5-6小时',
        cost: 200,
        description: '大雁塔+大唐不夜城+陕西历史博物馆联游。',
        highlights: ['陕西历史博物馆', '大雁塔登塔', '大唐不夜城全段', '唐风市井体验', '长安十二时辰主题街区'],
        tips: ['陕历博免费但需提前预约', '长安十二时辰门票约128元', '建议穿唐装汉服'],
      },
      {
        planName: '沉浸体验方案',
        planType: 'special',
        duration: '4-5小时',
        cost: 250,
        description: '沉浸式体验盛唐文化，穿越回长安。',
        highlights: ['唐装汉服租赁+妆造', '长安十二时辰主题街区', '大唐不夜城夜游', '唐风美食体验', '专业旅拍'],
        tips: ['汉服租赁+妆造约150-300元', '长安十二时辰建议工作日去', '提前预约旅拍服务'],
      },
    ],
  },

  // ============ 厦门 ============
  {
    scenicName: '鼓浪屿',
    city: '厦门',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '5-6小时',
        cost: 200,
        description: '经典鼓浪屿一日游，打卡必去景点和网红店铺。',
        highlights: ['日光岩登顶俯瞰全岛', '菽庄花园', '皓月园', '龙头路美食街', '万国建筑群漫步'],
        tips: ['往返船票35元+日光岩60元+菽庄花园30元', '提前在微信预约船票', '建议早上第一班船上岛'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '4-5小时',
        cost: 80,
        description: '免费漫步鼓浪屿，感受小岛风情。',
        highlights: ['免费海滩漫步', '万国建筑外观欣赏', '龙头路小吃', '小巷探秘', '海边日落'],
        tips: ['船票35元是必须的', '不进收费景点也能玩得很好', '自带水和零食'],
      },
      {
        planName: '深度文化方案',
        planType: 'deep',
        duration: '全天（8-10小时）',
        cost: 350,
        description: '深度探索鼓浪屿的音乐文化和建筑历史。',
        highlights: ['风琴博物馆', '钢琴博物馆', '菽庄花园', '日光岩', '国际刻字馆', '鼓浪屿音乐厅', '岛上民宿住一晚'],
        tips: ['联票100元含多个景点', '岛上住宿价格较高', '建议住一晚，清晨的鼓浪屿最美'],
      },
      {
        planName: '文艺浪漫方案',
        planType: 'special',
        duration: '5-6小时',
        cost: 250,
        description: '专为文艺青年和情侣设计的浪漫小岛之旅。',
        highlights: ['最美转角拍照', '张三疯奶茶', '赵小姐的店', '海边咖啡馆下午茶', '环岛路骑行', '月光岩日落'],
        tips: ['最美转角上午人少', '赵小姐的店建议工作日去', '带一件薄外套（海风大）'],
      },
    ],
  },
  {
    scenicName: '南普陀寺',
    city: '厦门',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '2-3小时',
        cost: 0,
        description: '闽南佛教圣地，感受宁静祥和的禅意。',
        highlights: ['大雄宝殿', '天王殿', '大悲殿', '藏经阁', '素菜馆品尝素斋'],
        tips: ['免费开放', '需提前在公众号预约', '着装得体，不要穿短裤拖鞋'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '1-2小时',
        cost: 15,
        description: '快速参观核心殿宇，感受寺庙氛围。',
        highlights: ['天王殿', '大雄宝殿', '免费赠香', '寺庙周边漫步'],
        tips: ['完全免费', '自带水', '可以请一串佛珠做纪念'],
      },
      {
        planName: '深度禅修方案',
        planType: 'deep',
        duration: '4-5小时',
        cost: 80,
        description: '南普陀寺+厦门大学+五老峰联游。',
        highlights: ['南普陀寺全寺', '五老峰登顶', '厦门大学外观', '南普陀素菜', '摩崖石刻'],
        tips: ['五老峰台阶较多，穿运动鞋', '南普陀素菜很有名，人均50元', '厦大需提前预约'],
      },
      {
        planName: '素斋体验方案',
        planType: 'special',
        duration: '3-4小时',
        cost: 100,
        description: '以南普陀素斋为核心的美食文化体验。',
        highlights: ['南普陀寺参观', '素斋馆用餐', '禅茶体验', '佛事观摩', '请购素饼伴手礼'],
        tips: ['素斋馆午餐11:00-13:00', '南普陀素饼是厦门特产', '用餐需排队，建议避开高峰'],
      },
    ],
  },
  {
    scenicName: '曾厝垵',
    city: '厦门',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '2-3小时',
        cost: 60,
        description: '厦门最文艺的渔村，美食与文创的天堂。',
        highlights: ['曾厝垵文创街', '渔村风情体验', '特色小吃品尝', '手工艺品选购', '海边日落'],
        tips: ['免费开放', '傍晚去最热闹', '巷子很深容易迷路，跟着人流走'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '1-2小时',
        cost: 25,
        description: '低成本感受曾厝垵的文艺氛围。',
        highlights: ['巷子漫步拍照', '一份沙茶面+一份海蛎煎', '文创小店逛逛', '免费沙滩'],
        tips: ['小吃比外面贵，可以少量品尝', '文创店可以只看不买', '海边免费'],
      },
      {
        planName: '深度文创方案',
        planType: 'deep',
        duration: '4-5小时',
        cost: 150,
        description: '深入了解曾厝垵的文创生态和渔村历史。',
        highlights: ['曾厝垵文创村全览', '独立书店', '手作工坊体验', '渔村民宿', '环岛路骑行', '音乐广场'],
        tips: ['部分工坊需预约', '建议住一晚渔村民宿', '环岛路骑行约30元/小时'],
      },
      {
        planName: '美食探店方案',
        planType: 'special',
        duration: '3-4小时',
        cost: 100,
        description: '曾厝垵及周边的美食深度探索。',
        highlights: ['曾厝垵小吃街', '沙茶面', '海蛎煎', '花生汤', '土笋冻', '旁边珍珠湾海鲜'],
        tips: ['曾厝垵内小吃偏贵', '本地人推荐去旁边的八市', '土笋冻是厦门特色，敢不敢试试'],
      },
    ],
  },
  {
    scenicName: '环岛路',
    city: '厦门',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '3-4小时',
        cost: 60,
        description: '骑行环岛路，感受厦门最美的海岸线。',
        highlights: ['自行车骑行', '白城沙滩', '音乐广场', '胡里山炮台', '会展中心海滩'],
        tips: ['租车约30-50元/天', '建议下午4-6点去，光线好且不热', '注意防晒'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '2-3小时',
        cost: 20,
        description: '步行+公共交通体验环岛路精华段。',
        highlights: ['白城沙滩免费', '音乐广场漫步', '海边栈道', '共享单车骑行一段'],
        tips: ['共享单车最便宜', '自带水和零食', '日落时分最美丽'],
      },
      {
        planName: '深度运动方案',
        planType: 'deep',
        duration: '5-6小时',
        cost: 120,
        description: '全程骑行环岛路，挑战自我。',
        highlights: ['全程骑行约20公里', '曾厝垵补给', '黄厝海滩', '五缘湾湿地公园', '观音山沙滩'],
        tips: ['全程骑行约3-4小时', '带足饮用水', '黄厝海滩适合游泳', '五缘湾可以看黑天鹅'],
      },
      {
        planName: '浪漫日落方案',
        planType: 'special',
        duration: '2-3小时',
        cost: 80,
        description: '专为情侣设计的浪漫海边日落之旅。',
        highlights: ['双人自行车骑行', '白城沙滩手牵手', '海边咖啡厅', '日落晚餐', '星空漫步'],
        tips: ['查好日落时间', '双人自行车约60元/小时', '带一件薄外套'],
      },
    ],
  },

  // ============ 杭州 ============
  {
    scenicName: '西湖',
    city: '杭州',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '4-5小时',
        cost: 100,
        description: '经典西湖十景游览，适合初次到访的游客。',
        highlights: ['断桥残雪', '白堤漫步', '三潭印月（游船）', '雷峰塔', '苏堤春晓', '花港观鱼'],
        tips: ['西湖免费，游船约55元，雷峰塔40元', '建议骑行环湖', '春季最佳，荷花季（6-9月）也推荐'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '3-4小时',
        cost: 20,
        description: '步行游览西湖核心区域，零门票畅游。',
        highlights: ['断桥', '白堤', '苏堤', '湖滨步行街', '音乐喷泉'],
        tips: ['西湖完全免费', '共享单车10元可以骑很久', '自带水和零食'],
      },
      {
        planName: '深度文化方案',
        planType: 'deep',
        duration: '全天（8-10小时）',
        cost: 250,
        description: '西湖+周边博物馆+茶园，深度体验杭州文化。',
        highlights: ['西湖全湖游览', '中国茶叶博物馆', '浙江省博物馆', '龙井茶园', '灵隐寺', '岳王庙'],
        tips: ['建议分两天游览', '博物馆免费但需预约', '龙井村可以品茶买茶'],
      },
      {
        planName: '浪漫情侣方案',
        planType: 'special',
        duration: '4-5小时',
        cost: 150,
        description: '专为情侣设计的西湖浪漫之旅。',
        highlights: ['断桥牵手', '手摇船游湖', '雷峰塔看日落', '西泠桥畔漫步', '湖畔餐厅晚餐'],
        tips: ['手摇船约150元/小时', '雷峰塔日落时间提前查好', '建议傍晚开始游览'],
      },
    ],
  },
  {
    scenicName: '灵隐寺',
    city: '杭州',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '3-4小时',
        cost: 95,
        description: '杭州最著名的佛教寺院，千年古刹的禅意之旅。',
        highlights: ['飞来峰石刻', '天王殿', '大雄宝殿', '药师殿', '法物流通处请手串'],
        tips: ['飞来峰45元+灵隐寺30元+香花券20元', '建议早上8点前到，人少清净', '穿舒适的鞋子'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '2-3小时',
        cost: 75,
        description: '只看核心景点，感受灵隐寺的庄严。',
        highlights: ['飞来峰石刻', '灵隐寺主殿', '免费赠香三支', '寺庙周边漫步'],
        tips: ['飞来峰是必买的门票', '灵隐寺门票30元', '自带水'],
      },
      {
        planName: '深度禅修方案',
        planType: 'deep',
        duration: '全天（6-8小时）',
        cost: 200,
        description: '灵隐寺+永福寺+韬光寺+北高峰联游。',
        highlights: ['灵隐寺全寺', '永福寺（清幽）', '韬光寺（登高）', '北高峰索道', '灵隐素斋'],
        tips: ['永福寺和韬光寺免费', '北高峰索道往返40元', '灵隐素斋很有名'],
      },
      {
        planName: '祈福许愿方案',
        planType: 'special',
        duration: '3-4小时',
        cost: 120,
        description: '以祈福许愿为主题的灵隐寺之旅。',
        highlights: ['请香祈福', '法物流通处请手串', '观音殿许愿', '写祈福牌', '品尝素斋'],
        tips: ['请香在寺内购买', '法物流通处可以请十八籽手串', '素斋午餐约30元/人'],
      },
    ],
  },
  {
    scenicName: '西溪湿地',
    city: '杭州',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '4-5小时',
        cost: 160,
        description: '城市中的天然湿地，感受"曲水弯环、群山四绕"的意境。',
        highlights: ['摇橹船游览', '深潭口', '河渚街', '高庄', '湿地植物园'],
        tips: ['门票80元+摇橹船约60元/人', '建议周家村入口进', '秋季芦苇最美'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '3-4小时',
        cost: 80,
        description: '步行游览免费区域，感受湿地自然风光。',
        highlights: ['免费区域步行', '河渚街逛吃', '观鸟', '湿地花海'],
        tips: ['部分区域免费开放', '自带午餐', '秋季去最美'],
      },
      {
        planName: '深度生态方案',
        planType: 'deep',
        duration: '全天（6-8小时）',
        cost: 300,
        description: '深度探索西溪湿地的生态和人文。',
        highlights: ['全程摇橹船', '烟水渔庄', '秋芦飞雪', '龙舟胜会', '湿地博物馆', '洪园'],
        tips: ['全程摇橹船约200元/船', '秋季11-12月芦苇最美', '带望远镜观鸟'],
      },
      {
        planName: '摄影创作方案',
        planType: 'special',
        duration: '5-6小时',
        cost: 200,
        description: '专为摄影爱好者设计的湿地拍摄之旅。',
        highlights: ['晨雾中的摇橹船', '芦苇荡日落', '白鹭飞翔', '水乡民居', '秋色红叶'],
        tips: ['建议清晨入园', '带长焦镜头拍鸟', '秋季色彩最丰富'],
      },
    ],
  },
  {
    scenicName: '河坊街',
    city: '杭州',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '2-3小时',
        cost: 60,
        description: '杭州最著名的历史文化街区，感受南宋御街的繁华。',
        highlights: ['胡庆余堂', '王星记扇子', '张小泉剪刀', '定胜糕', '龙须糖'],
        tips: ['免费开放', '建议傍晚去，灯光很美', '和南宋御街连在一起逛'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '1-2小时',
        cost: 20,
        description: '快速感受河坊街的历史氛围和美食。',
        highlights: ['街道漫步', '一份定胜糕+一杯藕粉', '老字号店铺外观', '免费拍照'],
        tips: ['免费开放', '小吃可以少量品尝', '部分老店只看不买也很有趣'],
      },
      {
        planName: '深度文化方案',
        planType: 'deep',
        duration: '4-5小时',
        cost: 120,
        description: '河坊街+南宋御街+吴山广场联游。',
        highlights: ['河坊街', '南宋御街', '胡庆余堂中药博物馆', '吴山广场', '城隍阁', '朱炳仁铜雕博物馆'],
        tips: ['胡庆余堂博物馆免费', '城隍阁门票30元', '建议穿舒适的鞋子'],
      },
      {
        planName: '美食探店方案',
        planType: 'special',
        duration: '3-4小时',
        cost: 100,
        description: '以河坊街为中心的杭州美食探索。',
        highlights: ['知味观小笼包', '奎元馆片儿川', '定胜糕', '葱包桧', '西湖藕粉', '龙井虾仁'],
        tips: ['知味观和奎元馆是老字号', '葱包桧是杭州特色小吃', '建议多人分食'],
      },
    ],
  },

  // ============ 重庆 ============
  {
    scenicName: '洪崖洞',
    city: '重庆',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '2-3小时',
        cost: 0,
        description: '重庆最具代表性的网红景点，现实版"千与千寻"。',
        highlights: ['洪崖洞全景', '千厮门大桥拍照', '嘉陵江边夜游', '11楼城市阳台', '吊脚楼建筑群'],
        tips: ['免费开放', '晚上7-10点灯光最美', '建议从千厮门大桥上拍全景'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '1-2小时',
        cost: 15,
        description: '零成本感受重庆夜景的魅力。',
        highlights: ['洪崖洞外观', '千厮门大桥拍照', '嘉陵江边散步', '一碗酸辣粉'],
        tips: ['完全免费', '自带水', '桥上拍照注意安全'],
      },
      {
        planName: '深度夜景方案',
        planType: 'deep',
        duration: '4-5小时',
        cost: 200,
        description: '洪崖洞+两江游船+解放碑联游，全方位感受重庆夜景。',
        highlights: ['洪崖洞', '两江游船', '解放碑', '大剧院江边', '朝天门码头'],
        tips: ['两江游船约150元', '建议先逛解放碑再步行到洪崖洞', '游船需提前购票'],
      },
      {
        planName: '美食夜景方案',
        planType: 'special',
        duration: '3-4小时',
        cost: 120,
        description: '以洪崖洞为中心的重庆美食夜景之旅。',
        highlights: ['洪崖洞4楼美食街', '洞子火锅', '嘉陵江边烤鱼', '千厮门大桥夜景', '解放碑八一好吃街'],
        tips: ['洪崖洞内餐饮偏贵', '建议到附近小巷吃更地道', '洞子火锅体验独特'],
      },
    ],
  },
  {
    scenicName: '磁器口古镇',
    city: '重庆',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '3-4小时',
        cost: 50,
        description: '千年古镇，感受老重庆的码头文化和巴渝风情。',
        highlights: ['宝轮寺', '钟家院', '古街漫步', '陈麻花', '手工酸辣粉'],
        tips: ['免费开放', '建议工作日去，周末人非常多', '地铁1号线磁器口站直达'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '2-3小时',
        cost: 25,
        description: '低成本感受磁器口的历史韵味。',
        highlights: ['古街免费漫步', '陈麻花试吃', '江边散步', '免费拍照打卡'],
        tips: ['免费开放', '陈麻花可以免费试吃', '自带水'],
      },
      {
        planName: '深度文化方案',
        planType: 'deep',
        duration: '5-6小时',
        cost: 150,
        description: '磁器口+歌乐山+白公馆渣滓洞联游。',
        highlights: ['磁器口古镇', '宝轮寺', '歌乐山森林公园', '白公馆', '渣滓洞', '磁器口后街'],
        tips: ['白公馆渣滓洞免费但需预约', '歌乐山需要爬山', '建议穿运动鞋'],
      },
      {
        planName: '美食探店方案',
        planType: 'special',
        duration: '3-4小时',
        cost: 80,
        description: '磁器口及周边的重庆特色美食探索。',
        highlights: ['陈麻花（必买）', '手工酸辣粉', '毛血旺', '鸡杂', '磁器口老火锅', '糍粑'],
        tips: ['陈昌银和陈建平两家麻花最出名', '毛血旺是磁器口招牌菜', '古镇内价格略贵'],
      },
    ],
  },
  {
    scenicName: '长江索道',
    city: '重庆',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '1-2小时',
        cost: 30,
        description: '重庆独有的"空中公交"，飞渡长江的震撼体验。',
        highlights: ['索道飞渡长江', '俯瞰两岸城市风光', '南岸站拍照', '渝中半岛全景'],
        tips: ['单程20元，往返30元', '建议从渝中新华路站到南岸', '排队时间可能较长'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '1小时',
        cost: 20,
        description: '单程体验长江索道的核心魅力。',
        highlights: ['单程索道体验', '两岸风光', '索道站拍照'],
        tips: ['单程20元', '用重庆公交卡更便宜', '避开早晚高峰排队少'],
      },
      {
        planName: '深度城市方案',
        planType: 'deep',
        duration: '4-5小时',
        cost: 100,
        description: '长江索道+南岸弹子石老街+龙门浩老街联游。',
        highlights: ['长江索道往返', '弹子石老街', '龙门浩老街', '长嘉汇购物公园', '南滨路江边'],
        tips: ['弹子石老街免费', '南滨路夜景很美', '建议下午出发，可以看日落'],
      },
      {
        planName: '摄影创作方案',
        planType: 'special',
        duration: '2-3小时',
        cost: 60,
        description: '专为摄影爱好者设计的索道拍摄之旅。',
        highlights: ['索道内部拍摄', '日落时分飞渡', '南岸站最佳拍摄点', '夜景索道', '两岸城市天际线'],
        tips: ['日落时分光线最美', '南岸站出来是最佳拍摄点', '带上广角镜头'],
      },
    ],
  },
  {
    scenicName: '解放碑',
    city: '重庆',
    plans: [
      {
        planName: '主流游览方案',
        planType: 'mainstream',
        duration: '2-3小时',
        cost: 50,
        description: '重庆的地标性建筑，中国唯一一座纪念抗战胜利的纪念碑。',
        highlights: ['解放碑合影', '八一好吃街', '国泰艺术中心', '民权路步行街', '环球购物中心'],
        tips: ['免费开放', '晚上灯光更漂亮', '八一好吃街在附近'],
      },
      {
        planName: '经济实惠方案',
        planType: 'economy',
        duration: '1-2小时',
        cost: 20,
        description: '快速打卡解放碑，感受重庆的都市繁华。',
        highlights: ['解放碑拍照', '八一好吃街小吃', '步行街逛逛'],
        tips: ['免费拍照', '八一好吃街小吃便宜', '自带水'],
      },
      {
        planName: '深度购物方案',
        planType: 'deep',
        duration: '4-5小时',
        cost: 300,
        description: '解放碑+洪崖洞+朝天门联游，重庆都市核心区全覆盖。',
        highlights: ['解放碑', '洪崖洞', '朝天门来福士', '八一好吃街', '魁星楼', '山城步道'],
        tips: ['三个景点步行可达', '来福士可以逛商场', '山城步道免费且很有特色'],
      },
      {
        planName: '美食购物方案',
        planType: 'special',
        duration: '3-4小时',
        cost: 150,
        description: '以解放碑为中心的重庆美食和购物体验。',
        highlights: ['八一好吃街', '洞子火锅', '重庆小面', '酸辣粉', '山城小汤圆', '特产采购'],
        tips: ['八一好吃街品种齐全', '火锅推荐洞子火锅', '火锅底料是最佳伴手礼'],
      },
    ],
  },
]
