/**
 * 用户评价 Mock 数据
 * 覆盖 scenic / food / trip 三种类型，内容真实感强
 * 共 52 条评价，覆盖汕头、成都、长沙、西安、厦门、杭州、重庆、北京、上海、广州、武汉、哈尔滨、云南等多个城市
 */
import type { Review } from '@/types'

export const mockReviews: Review[] = [
  // ---- 景点评价 ----
  {
    id: 'review-1',
    targetType: 'scenic',
    targetId: 'scenic-1',
    targetName: '南澳岛',
    userId: 'user-1',
    userName: '海风旅人',
    rating: 5,
    content: '南澳岛真的太美了！环岛公路一路风景如画，青澳湾的沙滩细腻干净，海水清澈见底。日落时分在灯塔旁拍照，随手一拍就是大片。建议租一辆电动车环岛，慢慢逛，每个海湾都值得停下来。岛上物价也很亲民，海鲜大排档新鲜又便宜。',
    tags: ['值得推荐', '风景绝美', '适合拍照'],
    likes: 42,
    liked: false,
    createdAt: '2025-12-15T10:30:00Z',
  },
  {
    id: 'review-2',
    targetType: 'scenic',
    targetId: 'scenic-2',
    targetName: '汕头小公园',
    userId: 'user-2',
    userName: '城市漫步者',
    rating: 4,
    content: '骑楼建筑群很有民国风情，修缮后焕然一新。老妈宫粽球和飘香小吃都在附近，边逛边吃很惬意。不过节假日人太多了，拍照要找角度避开人群。建议工作日去，体验会好很多。晚上灯光亮起来后更有氛围感。',
    tags: ['文化底蕴', '美食集中'],
    likes: 28,
    liked: true,
    createdAt: '2025-12-20T14:20:00Z',
  },
  {
    id: 'review-3',
    targetType: 'scenic',
    targetId: 'scenic-1',
    targetName: '南澳岛',
    userId: 'user-3',
    userName: '背包客小陈',
    rating: 4,
    content: '整体体验不错，但旺季住宿比较紧张，建议提前预订。风很大，记得带件外套。青澳湾适合游泳，后宅湾更适合看日出。岛上交通不太方便，没有公交，要么租车要么包车。海鲜推荐去后宅镇上的大排档，比景区的实惠很多。',
    tags: ['值得推荐', '注意防风'],
    likes: 15,
    liked: false,
    createdAt: '2026-01-05T09:15:00Z',
  },

  // ---- 美食评价（汕头） ----
  {
    id: 'review-4',
    targetType: 'food',
    targetId: 'food-1',
    targetName: '牛肉火锅',
    userId: 'user-4',
    userName: '吃货阿杰',
    rating: 5,
    content: '牛肉火锅真的绝了，吊龙入口即化，胸口油脆脆的很有嚼劲，匙柄嫩滑多汁。汤底就是清水加萝卜玉米，完全靠牛肉本身的鲜味。涮的时候师傅会教你每个部位烫几秒，这种仪式感太棒了。人均80左右，性价比超高。强烈推荐吊龙和五花趾！',
    tags: ['值得推荐', '味道惊艳', '性价比高'],
    likes: 67,
    liked: false,
    createdAt: '2025-12-18T20:45:00Z',
  },
  {
    id: 'review-5',
    targetType: 'food',
    targetId: 'food-2',
    targetName: '蚝烙',
    userId: 'user-5',
    userName: '小吃达人',
    rating: 4,
    content: '老妈宫的蚝烙确实名不虚传，外皮酥脆，里面的蚝肉肥美多汁。鱼露的味道很特别，第一次吃可能不太习惯，但配上芫荽就很香。25块钱一份分量很足，两个人吃刚好。建议趁热吃，凉了就不够酥了。',
    tags: ['值得推荐', '地道小吃'],
    likes: 33,
    liked: true,
    createdAt: '2025-12-22T11:30:00Z',
  },
  {
    id: 'review-6',
    targetType: 'food',
    targetId: 'food-3',
    targetName: '夜粥（打冷）',
    userId: 'user-6',
    userName: '深夜觅食者',
    rating: 5,
    content: '打冷绝对是汕头美食的灵魂！上百种冷盘随便挑，卤鹅软烂入味，生腌虾鲜甜弹牙，鱼饭肉质紧实。人均40块就能吃到撑，而且都是新鲜现做的。环境虽然一般，但这就是街头美食的魅力啊。晚上10点后才开始营业，真正的深夜食堂。每次来汕头都要来吃一次。',
    tags: ['值得推荐', '性价比高', '深夜美食'],
    likes: 51,
    liked: false,
    createdAt: '2026-01-02T23:10:00Z',
  },
  {
    id: 'review-7',
    targetType: 'food',
    targetId: 'food-4',
    targetName: '老妈宫粽球',
    userId: 'user-7',
    userName: '早餐爱好者',
    rating: 4,
    content: '甜咸双拼的粽球真的很有创意，一半甜一半咸，一口下去两种味道在嘴里融合。豆沙细腻，五花肉入味，栗子粉糯。15块钱一个分量很足，当早餐吃完全够了。不过建议早点去，下午去经常卖完了。',
    tags: ['值得推荐', '早餐首选', '限量供应'],
    likes: 22,
    liked: false,
    createdAt: '2026-01-08T08:00:00Z',
  },

  // ---- 行程评价 ----
  {
    id: 'review-8',
    targetType: 'trip',
    targetId: 'trip-1',
    targetName: '汕头3日美食之旅',
    userId: 'user-8',
    userName: '旅行规划师',
    rating: 5,
    content: '这个行程安排得太合理了！Day1逛老城区吃小吃，Day2南澳岛环岛，Day3牛肉火锅+特产采购。节奏不紧不慢，每天都能吃到当地特色美食。住宿推荐选在金平区，去哪里都方便。预算控制得很好，3天人均不到1500。强烈推荐给第一次来汕头的朋友！',
    tags: ['值得推荐', '安排合理', '预算友好'],
    likes: 38,
    liked: false,
    createdAt: '2026-01-10T16:30:00Z',
  },
  {
    id: 'review-9',
    targetType: 'trip',
    targetId: 'trip-1',
    targetName: '汕头3日美食之旅',
    userId: 'user-9',
    userName: '周末出游党',
    rating: 4,
    content: '整体行程不错，但Day2南澳岛那天稍微有点赶，建议多留半天时间。跨海大桥收费有点贵，来回100多。岛上租电动车要带驾照，我们没带只能包车，多花了不少钱。不过风景确实很美，美食也都没踩雷。下次来会调整一下节奏，慢慢玩。',
    tags: ['值得推荐', '注意交通'],
    likes: 19,
    liked: true,
    createdAt: '2026-01-12T21:00:00Z',
  },
  {
    id: 'review-10',
    targetType: 'trip',
    targetId: 'trip-2',
    targetName: '潮州文化深度游',
    userId: 'user-10',
    userName: '历史迷小李',
    rating: 5,
    content: '潮州古城真的太有味道了！广济桥的"十八梭船廿四洲"设计绝妙，每天傍晚浮桥断开通航的仪式感满满。牌坊街虽然商业化了一些，但古建筑保存得很好。开元寺很安静，适合慢慢逛。潮州菜比汕头菜更精致，卤鹅和春饼必吃。强烈推荐住一晚古城里的民宿，清晨的古城最美。',
    tags: ['值得推荐', '文化底蕴', '适合慢游'],
    likes: 45,
    liked: false,
    createdAt: '2026-01-15T13:45:00Z',
  },

  // ---- 成都美食评价（3条） ----
  {
    id: 'review-11',
    targetType: 'food',
    targetId: 'food-5',
    targetName: '串串香',
    userId: 'user-11',
    userName: '成都吃货王',
    rating: 5,
    content: '马路边边的串串香真的太有氛围了！坐在小马扎上，围着铁锅涮串串，瞬间穿越回80年代的成都。麻辣牛肉是必点的，辣得过瘾又停不下来。鲜毛肚七上八下涮几秒就吃，脆嫩爽口。最后一定要来一碗冰粉解辣，红糖冰粉配上山楂碎和葡萄干，完美收尾。人均60块，吃到扶墙出！',
    tags: ['值得推荐', '氛围感满分', '性价比高'],
    likes: 56,
    liked: false,
    createdAt: '2026-01-20T21:30:00Z',
  },
  {
    id: 'review-12',
    targetType: 'food',
    targetId: 'food-6',
    targetName: '担担面',
    userId: 'user-12',
    userName: '面食爱好者',
    rating: 4,
    content: '洞子口张老二的担担面果然名不虚传！面条筋道，臊子炒得喷香，红油辣而不燥。最惊喜的是甜水面，又粗又硬的面条裹满红糖辣酱，甜辣交织的口感太独特了。钟水饺也推荐，皮薄馅大，红油味正。20块钱就能吃到三样经典小吃，成都的物价太感人了。建议工作日去，周末排队很久。',
    tags: ['值得推荐', '地道老店', '价格实惠'],
    likes: 34,
    liked: true,
    createdAt: '2026-02-01T12:15:00Z',
  },
  {
    id: 'review-13',
    targetType: 'food',
    targetId: 'food-8',
    targetName: '冒菜',
    userId: 'user-13',
    userName: '一个人的旅行',
    rating: 5,
    content: '三顾冒菜真的是"一个人的火锅"天花板！冒牛肉大片厚实，入口麻辣鲜香；冒千层肚脆嫩弹牙，裹满红油蒜泥。配上一碗白米饭，把红油汤汁拌进饭里，简直是人间美味。玉林路这家店开了很多年，底料配方一直没变，每次来成都都要来吃。35块钱一份冒菜加米饭，管饱又管好。',
    tags: ['值得推荐', '一个人也能吃好', '味道正宗'],
    likes: 41,
    liked: false,
    createdAt: '2026-02-10T19:00:00Z',
  },

  // ---- 西安景点评价（2条） ----
  {
    id: 'review-14',
    targetType: 'scenic',
    targetId: 'scenic-xian-1',
    targetName: '秦始皇兵马俑',
    userId: 'user-14',
    userName: '历史控小张',
    rating: 5,
    content: '亲眼看到兵马俑的那一刻真的被震撼到了！一号坑的规模太大了，几千个兵俑排列整齐，每个面部表情都不一样，两千多年前的工艺简直不可思议。强烈建议请讲解员，不然就是看一堆泥人。二号坑的跪射俑和骑兵阵也很精彩，铜车马展厅的铜车工艺更是精美绝伦。门票120元绝对值回票价。',
    tags: ['值得推荐', '震撼人心', '必请讲解'],
    likes: 73,
    liked: false,
    createdAt: '2026-02-15T14:00:00Z',
  },
  {
    id: 'review-15',
    targetType: 'scenic',
    targetId: 'scenic-xian-4',
    targetName: '大唐不夜城',
    userId: 'user-15',
    userName: '夜游达人',
    rating: 4,
    content: '大唐不夜城的夜景真的太美了！整条街灯火辉煌，仿佛穿越回了盛唐长安。不倒翁小姐姐的表演很精彩，互动感很强，但排队拍照要等很久。花车巡游和诗词互动区也很有意思。最关键的是免费开放！建议晚上7点以后去，灯光全开最漂亮。周边的餐厅价格偏贵，建议吃饱了再来逛。',
    tags: ['值得推荐', '夜景绝美', '免费开放'],
    likes: 48,
    liked: true,
    createdAt: '2026-02-20T20:30:00Z',
  },

  // ---- 厦门评价（2条） ----
  {
    id: 'review-16',
    targetType: 'scenic',
    targetId: 'scenic-xm-1',
    targetName: '鼓浪屿',
    userId: 'user-16',
    userName: '文艺小清新',
    rating: 4,
    content: '鼓浪屿真的很适合慢慢逛！日光岩登顶后可以俯瞰全岛和厦门市区，视野超棒。万国建筑群很有异域风情，每栋别墅都有故事。龙头路的小吃很多，张三疯奶茶和赵小姐的店是必打卡的。不过周末人真的太多了，建议工作日来。船票一定要提前在微信上预约，现场买票经常没位。',
    tags: ['值得推荐', '适合慢游', '注意预约船票'],
    likes: 37,
    liked: false,
    createdAt: '2026-03-01T16:00:00Z',
  },
  {
    id: 'review-17',
    targetType: 'food',
    targetId: 'food-xm-1',
    targetName: '沙茶面',
    userId: 'user-17',
    userName: '面食猎人',
    rating: 5,
    content: '厦门的沙茶面真的太好吃了！汤底用沙茶酱、花生、虾米等十几种材料熬制，浓郁鲜香，微甜微辣。面条用的是碱面，口感爽滑。配料可以自己选，豆腐、猪肝、大肠、虾仁都很新鲜。乌糖沙茶面是本地人最推荐的老店，虽然店面很小但味道正宗。人均20块就能吃到一碗满满当当的沙茶面，厦门美食性价比之王！',
    tags: ['值得推荐', '味道惊艳', '本地人推荐'],
    likes: 29,
    liked: false,
    createdAt: '2026-03-05T11:30:00Z',
  },

  // ---- 杭州评价（2条） ----
  {
    id: 'review-18',
    targetType: 'scenic',
    targetId: 'scenic-hz-1',
    targetName: '西湖',
    userId: 'user-18',
    userName: '江南客',
    rating: 5,
    content: '西湖真的不愧是人间天堂！断桥残雪虽然没赶上雪景，但春天的断桥桃红柳绿也很美。白堤漫步特别舒服，两边都是桃花和垂柳。强烈推荐坐手摇船游湖，船夫会讲西湖的传说故事，150元一小时很值。雷峰塔登上去可以看西湖全景，傍晚去还能看日落。西湖完全免费，杭州对游客太友好了。',
    tags: ['值得推荐', '免费景点', '四季皆美'],
    likes: 62,
    liked: true,
    createdAt: '2026-03-10T15:00:00Z',
  },
  {
    id: 'review-19',
    targetType: 'food',
    targetId: 'food-hz-1',
    targetName: '片儿川',
    userId: 'user-19',
    userName: '杭州土著',
    rating: 4,
    content: '奎元馆的片儿川是杭州人的骄傲！面条是手工现擀的，又宽又薄，口感滑嫩。浇头是笋片、雪菜和瘦肉，笋片脆嫩鲜甜，雪菜咸香开胃，汤底清澈鲜美。一碗片儿川15块钱，在景区附近算很良心了。建议加一份爆鳝，鳝鱼段炸得外酥里嫩，拌进面里绝了。百年老店的味道确实不一样。',
    tags: ['值得推荐', '百年老店', '杭州必吃'],
    likes: 25,
    liked: false,
    createdAt: '2026-03-15T12:00:00Z',
  },

  // ---- 重庆评价（1条） ----
  {
    id: 'review-20',
    targetType: 'scenic',
    targetId: 'scenic-cq-1',
    targetName: '洪崖洞',
    userId: 'user-20',
    userName: '山城探险家',
    rating: 4,
    content: '洪崖洞的夜景真的像千与千寻里的场景！从千厮门大桥上拍全景最出片，灯火辉煌的吊脚楼层层叠叠，倒映在嘉陵江面上，太梦幻了。不过里面人真的超级多，尤其是周末晚上，几乎是摩肩接踵。建议从11楼的城市阳台进入，一层一层往下逛，最后到嘉陵江边。洞子火锅体验很独特，在防空洞里吃火锅，重庆人太会利用地形了。',
    tags: ['值得推荐', '夜景绝美', '人多注意安全'],
    likes: 44,
    liked: false,
    createdAt: '2026-03-20T22:00:00Z',
  },

  // ---- 北京美食评价（4条） ----
  {
    id: 'review-21',
    targetType: 'food',
    targetId: 'food-bj-1',
    targetName: '北京烤鸭',
    userId: 'user-21',
    userName: '京城美食家',
    rating: 5,
    content: '大董的烤鸭真的名不虚传！鸭皮酥脆得像玻璃一样，入口即化，蘸白糖吃是绝配。鸭肉嫩滑多汁，配上葱丝、黄瓜条和甜面酱，卷在薄饼里一口咬下去，层次感太丰富了。服务员会现场片鸭，刀工精湛，每一片都带皮带肉。人均200多，虽然不便宜但绝对值得。建议提前预约，现场排队至少一小时。',
    tags: ['值得推荐', '味道惊艳', '需提前预约'],
    likes: 89,
    liked: false,
    createdAt: '2025-11-10T19:30:00Z',
  },
  {
    id: 'review-22',
    targetType: 'food',
    targetId: 'food-bj-2',
    targetName: '炸酱面',
    userId: 'user-22',
    userName: '胡同串子',
    rating: 4,
    content: '海碗居的炸酱面太地道了！面条是手擀的，粗细均匀有嚼劲。炸酱用五花肉丁和黄酱慢火熬制，酱香浓郁。配菜有黄瓜丝、豆芽、萝卜丝等七八种，拌在一起色彩缤纷。最关键的是面条可以无限续，大碗才22块钱，在北京这个物价简直是良心价。店里环境很接地气，塑料凳子小方桌，就是老北京的感觉。',
    tags: ['值得推荐', '价格实惠', '老北京味道'],
    likes: 36,
    liked: false,
    createdAt: '2025-11-25T12:45:00Z',
  },
  {
    id: 'review-23',
    targetType: 'food',
    targetId: 'food-bj-3',
    targetName: '豆汁焦圈',
    userId: 'user-23',
    userName: '猎奇食客',
    rating: 3,
    content: '护国寺小吃的豆汁真的需要勇气！味道酸酸的带点发酵的怪味，第一次喝差点吐出来。但配上酥脆的焦圈和辣咸菜丝，居然越喝越上瘾。老北京人一天不喝豆汁就不自在，我们外地人确实需要适应。焦圈倒是很好吃，金黄酥脆，5块钱三个。建议先买一小碗试试，别一上来就大碗。',
    tags: ['需要勇气', '老北京特色', '因人而异'],
    likes: 27,
    liked: false,
    createdAt: '2025-12-05T08:30:00Z',
  },
  {
    id: 'review-24',
    targetType: 'food',
    targetId: 'food-bj-4',
    targetName: '涮羊肉',
    userId: 'user-24',
    userName: '铜锅爱好者',
    rating: 5,
    content: '东来顺的铜锅涮羊肉是冬天最幸福的事！清汤锅底就是葱姜枸杞，完全考验羊肉品质。手切鲜羊肉入锅变色就捞，蘸上芝麻酱、韭菜花和腐乳汁调的蘸料，鲜嫩到极致。糖蒜也是灵魂配菜，解腻又开胃。大冬天围着一个铜锅热气腾腾地涮肉，再喝二两小酒，这才是北京冬天的正确打开方式。人均150左右。',
    tags: ['值得推荐', '冬日必吃', '肉质鲜嫩'],
    likes: 54,
    liked: true,
    createdAt: '2026-01-08T18:00:00Z',
  },

  // ---- 上海美食评价（3条） ----
  {
    id: 'review-25',
    targetType: 'food',
    targetId: 'food-sh-1',
    targetName: '小笼包',
    userId: 'user-25',
    userName: '美食家阿花',
    rating: 5,
    content: '南翔馒头店的小笼包真的绝了！皮薄如纸，透过皮能看到里面晃动的汤汁。轻轻提起，慢慢咬开一个小口，吸掉鲜美的汤汁，再蘸醋和姜丝吃。蟹粉小笼更是一绝，蟹黄的鲜香和猪肉的醇厚完美融合。一笼8个28块钱，在上海这个价位很良心。建议早上去，排队人少，小笼包也是现蒸的最新鲜。',
    tags: ['值得推荐', '味道惊艳', '上海必吃'],
    likes: 71,
    liked: false,
    createdAt: '2025-10-20T09:00:00Z',
  },
  {
    id: 'review-26',
    targetType: 'food',
    targetId: 'food-sh-2',
    targetName: '生煎包',
    userId: 'user-26',
    userName: '上海小囡',
    rating: 4,
    content: '小杨生煎果然是上海生煎的天花板！底部煎得金黄焦脆，上面撒满芝麻和葱花。一口咬下去，汤汁四溢，猪肉馅鲜嫩多汁。最关键的是皮不会太厚，口感刚刚好。不过要注意，刚出锅的生煎包里面汤汁很烫，一定要先咬小口放气，不然会烫到嘴。一笼4个12块钱，当早餐吃太满足了。每个分店都要排队，建议避开高峰期。',
    tags: ['值得推荐', '注意烫嘴', '早餐首选'],
    likes: 45,
    liked: false,
    createdAt: '2025-11-15T08:15:00Z',
  },
  {
    id: 'review-27',
    targetType: 'food',
    targetId: 'food-sh-3',
    targetName: '葱油拌面',
    userId: 'user-27',
    userName: '碳水星人',
    rating: 4,
    content: '阿大葱油拌面虽然店面很小只有几张桌子，但味道真的没话说！葱油是用小葱慢火炸制，焦香扑鼻。面条裹满葱油和酱油，每根都油光发亮，拌匀后入口咸香回甘。加一份大排，炸得外酥里嫩，蘸着葱油吃太香了。人均25块就能吃饱，在上海算很实惠了。老板是个上海爷叔，态度有点傲但面确实好吃。建议下午2点前去，晚了经常卖完。',
    tags: ['值得推荐', '简单美味', '限量供应'],
    likes: 38,
    liked: true,
    createdAt: '2026-02-28T13:30:00Z',
  },

  // ---- 广州/武汉/西安美食评价（5条） ----
  {
    id: 'review-28',
    targetType: 'food',
    targetId: 'food-gz-1',
    targetName: '早茶',
    userId: 'user-28',
    userName: '饮茶达人',
    rating: 5,
    content: '广州的早茶文化真的太享受了！点都德的虾饺皇一笼四个，每只都有整只大虾仁，皮薄晶莹弹牙。凤爪蒸得软烂脱骨，豆豉味浓郁。流沙包掰开金沙流淌，甜而不腻。红米肠外皮软糯，里面裹着脆皮和虾仁，口感层次丰富。一壶铁观音配上几笼点心，和朋友聊聊天，这就是广州人最惬意的早晨。人均80左右，建议周末去体验氛围。',
    tags: ['值得推荐', '广式经典', '氛围感满分'],
    likes: 66,
    liked: false,
    createdAt: '2025-09-18T10:00:00Z',
  },
  {
    id: 'review-29',
    targetType: 'food',
    targetId: 'food-wh-1',
    targetName: '热干面',
    userId: 'user-29',
    userName: '武汉通小刘',
    rating: 5,
    content: '蔡林记的热干面是武汉人的命！面条是碱面，提前拌好香油晾凉，吃的时候再烫一下。芝麻酱是灵魂，浓稠香醇，拌开后每根面条都裹满酱汁。配上酸豆角、辣萝卜丁和葱花，咸香微辣，越吃越香。5块钱一碗，加个蛋和豆皮7块钱就能吃撑。武汉人早上端着纸碗边走边吃热干面，这才是最地道的武汉早餐。建议多加点辣萝卜丁，口感更丰富。',
    tags: ['值得推荐', '武汉必吃', '性价比之王'],
    likes: 82,
    liked: false,
    createdAt: '2026-03-01T07:45:00Z',
  },
  {
    id: 'review-30',
    targetType: 'food',
    targetId: 'food-xa-1',
    targetName: '肉夹馍',
    userId: 'user-30',
    userName: '馍夹一切',
    rating: 5,
    content: '回民街的老白家肉夹馍太香了！馍是现打的白吉馍，外皮烤得酥脆，里面松软。腊汁肉用老汤慢炖五六个小时，肥肉入口即化，瘦肉酥烂不柴。夹进馍里，肉汁渗入馍的层次中，咬一口满嘴留香。10块钱一个分量很足，男生吃两个才饱。建议要肥瘦相间的，纯瘦的有点干。搭配一碗凉皮，就是西安最经典的美食组合。',
    tags: ['值得推荐', '外酥里嫩', '西安必吃'],
    likes: 57,
    liked: true,
    createdAt: '2026-02-18T11:30:00Z',
  },
  {
    id: 'review-31',
    targetType: 'food',
    targetId: 'food-cq-1',
    targetName: '重庆火锅',
    userId: 'user-31',
    userName: '辣不怕',
    rating: 5,
    content: '珮姐老火锅的牛油锅底太正宗了！端上来就是满满一锅红油，花椒和干辣椒浮在上面，香气扑鼻。毛肚七上八下涮几秒，脆嫩弹牙；鸭肠烫卷了就吃，爽滑Q弹；嫩牛肉裹上蛋清，涮出来又嫩又滑。麻辣牛肉是重口味爱好者的最爱，辣到流泪但停不下来。最后来一碗红糖冰汤圆解辣，冰火两重天。人均100左右，重庆火锅的性价比真的高。',
    tags: ['值得推荐', '辣到过瘾', '重庆必吃'],
    likes: 93,
    liked: false,
    createdAt: '2026-01-25T20:00:00Z',
  },
  {
    id: 'review-32',
    targetType: 'food',
    targetId: 'food-cs-1',
    targetName: '臭豆腐',
    userId: 'user-32',
    userName: '长沙夜猫子',
    rating: 4,
    content: '火宫殿的臭豆腐闻着臭吃着香！外皮炸得黑乎乎的，咬开里面白白嫩嫩，像豆腐脑一样滑嫩。灌入辣椒蒜汁和酸萝卜丁，一口下去外酥里嫩，辣中带鲜。10块钱6片，在坡子街边走边吃很有氛围。黑色经典也是长沙本地人推荐的品牌，口味更重一些。建议趁热吃，凉了就不够脆了。第一次吃的人别被味道吓到，勇敢尝试一下！',
    tags: ['值得推荐', '长沙必吃', '闻臭吃香'],
    likes: 41,
    liked: false,
    createdAt: '2026-03-08T21:30:00Z',
  },

  // ---- 北京景点评价（3条） ----
  {
    id: 'review-33',
    targetType: 'scenic',
    targetId: 'scenic-bj-1',
    targetName: '故宫',
    userId: 'user-33',
    userName: '紫禁城迷',
    rating: 5,
    content: '故宫真的太宏伟了！从午门走进去的那一刻，红墙黄瓦的宫殿群在眼前铺展开来，瞬间感受到皇家的威严。太和殿前的广场大得让人震撼，想象古代朝会的场面一定很壮观。珍宝馆和钟表馆一定要看，里面的文物精美到令人叹为观止。建议租一个电子讲解器，边走边听每座宫殿的历史故事。门票60元，提前在官网预约即可。至少留半天时间慢慢逛。',
    tags: ['值得推荐', '震撼人心', '需提前预约'],
    likes: 105,
    liked: false,
    createdAt: '2025-10-05T09:30:00Z',
  },
  {
    id: 'review-34',
    targetType: 'scenic',
    targetId: 'scenic-bj-2',
    targetName: '长城',
    userId: 'user-34',
    userName: '不到长城非好汉',
    rating: 5,
    content: '慕田峪长城比八达岭人少很多，体验感好太多了！长城蜿蜒在山脊上，秋天红叶满山的时候景色绝美。建议坐缆车上到第14号敌楼，然后往两边走。往东走到第20号敌楼那段最险峻，有些台阶几乎垂直，爬上去很有成就感。长城上的风很大，记得带外套。下山可以坐滑道，穿过树林滑下来很刺激。门票+缆车往返大概120元，建议早点出发避开旅游团。',
    tags: ['值得推荐', '人少景美', '建议缆车上山'],
    likes: 78,
    liked: true,
    createdAt: '2025-10-20T08:00:00Z',
  },
  {
    id: 'review-35',
    targetType: 'scenic',
    targetId: 'scenic-bj-3',
    targetName: '颐和园',
    userId: 'user-35',
    userName: '园林爱好者',
    rating: 4,
    content: '颐和园的昆明湖真的太美了！十七孔桥在日落时分的金光穿洞景观令人叹为观止，每年冬至前后几天才能看到。长廊上的彩画有14000多幅，每一幅都是不同的故事，走完长廊就像看了一部连环画。建议坐船游湖，从不同的角度看佛香阁和万寿山，别有一番风味。门票30元，联票60元包含苏州街等景点。园子很大，建议留至少4个小时。',
    tags: ['值得推荐', '园林艺术', '日落最美'],
    likes: 52,
    liked: false,
    createdAt: '2025-12-22T15:00:00Z',
  },

  // ---- 上海景点评价（2条） ----
  {
    id: 'review-36',
    targetType: 'scenic',
    targetId: 'scenic-sh-1',
    targetName: '外滩',
    userId: 'user-36',
    userName: '魔都夜行者',
    rating: 5,
    content: '外滩的夜景真的无与伦比！站在黄浦江边，一边是万国建筑博览群的古典之美，一边是陆家嘴三件套的现代之光，古今交融的画面太震撼了。建议晚上7点到8点之间去，可以看到亮灯的过程。也可以花2块钱坐轮渡到对岸，从浦东看外滩全景更壮观。外滩全程免费开放，但节假日人非常多，建议工作日去。附近的南京路步行街也可以顺路逛逛。',
    tags: ['值得推荐', '夜景绝美', '免费开放'],
    likes: 96,
    liked: false,
    createdAt: '2025-11-08T19:30:00Z',
  },
  {
    id: 'review-37',
    targetType: 'scenic',
    targetId: 'scenic-sh-2',
    targetName: '豫园',
    userId: 'user-37',
    userName: '古典园林迷',
    rating: 4,
    content: '豫园是上海市区里难得的江南古典园林，虽然面积不大但设计精巧。假山、回廊、亭台楼阁错落有致，九曲桥和湖心亭是标志性景观。园内的玉玲珑太湖石是镇园之宝，据说有四百多年历史了。门票40元，建议工作日去人少一些。周边的城隍庙商圈很热闹，可以顺便吃南翔小笼包和梨膏糖。不过商业化气息比较重，想要安静赏园的话建议一开门就进去。',
    tags: ['值得推荐', '古典园林', '建议早去'],
    likes: 33,
    liked: false,
    createdAt: '2026-01-18T10:00:00Z',
  },

  // ---- 武汉/安徽景点评价（3条） ----
  {
    id: 'review-38',
    targetType: 'scenic',
    targetId: 'scenic-wh-1',
    targetName: '黄鹤楼',
    userId: 'user-38',
    userName: '诗词爱好者',
    rating: 4,
    content: '黄鹤楼虽然是在原址重建的，但气势依然恢宏。登上五楼顶层，可以俯瞰长江大桥和整个武昌城区，视野非常开阔。"昔人已乘黄鹤去，此地空余黄鹤楼"，站在楼上吟诵崔颢的诗，别有一番感慨。楼内的壁画和展览介绍了黄鹤楼的历史变迁，值得一看。门票70元，建议傍晚去，可以同时看日落和夜景。楼下的司门口黄鹤楼地铁站出口是网红拍照点，可以拍到黄鹤楼和城市的合影。',
    tags: ['值得推荐', '视野开阔', '文化地标'],
    likes: 47,
    liked: false,
    createdAt: '2026-02-05T17:00:00Z',
  },
  {
    id: 'review-39',
    targetType: 'scenic',
    targetId: 'scenic-ah-1',
    targetName: '黄山',
    userId: 'user-39',
    userName: '山野客',
    rating: 5,
    content: '黄山真的不愧是"天下第一奇山"！云海翻涌的时候，奇松怪石若隐若现，宛如仙境。迎客松果然名不虚传，千年古松傲然挺立在悬崖边上。光明顶看日出是必打卡的，凌晨4点起床爬山虽然辛苦，但看到太阳从云海中升起的那一刻，一切都值了。西海大峡谷的栈道修在悬崖峭壁上，走起来有点刺激但风景绝美。建议住山上，两天时间慢慢玩。门票190元，索道单程80元。',
    tags: ['值得推荐', '云海奇观', '建议住山上'],
    likes: 112,
    liked: false,
    createdAt: '2025-11-01T06:00:00Z',
  },
  {
    id: 'review-40',
    targetType: 'scenic',
    targetId: 'scenic-hn-1',
    targetName: '张家界',
    userId: 'user-40',
    userName: '阿凡达迷',
    rating: 5,
    content: '张家界国家森林公园的石英砂岩峰林地貌太震撼了！三千多座石峰拔地而起，云雾缭绕时真的像悬浮在空中的仙境，难怪阿凡达取景于此。天门山的玻璃栈道走起来腿有点软，但俯瞰万丈深渊的体验太刺激了。百龙天梯是世界上最高的户外观光电梯，326米的高度66秒就到山顶，科技感满满。建议玩4天，森林公园2天，天门山1天，大峡谷玻璃桥1天。门票套票大概500多元。',
    tags: ['值得推荐', '地貌奇观', '建议4天'],
    likes: 87,
    liked: true,
    createdAt: '2025-09-25T14:00:00Z',
  },

  // ---- 四川/云南景点评价（4条） ----
  {
    id: 'review-41',
    targetType: 'scenic',
    targetId: 'scenic-sc-1',
    targetName: '九寨沟',
    userId: 'user-41',
    userName: '水色迷恋者',
    rating: 5,
    content: '九寨沟的水真的美得不真实！五花海的颜色从翠绿到湛蓝渐变，清澈见底，枯木在水中排列出奇妙的图案。珍珠滩瀑布的水流从宽阔的钙华滩上奔涌而下，水花飞溅如珍珠散落。诺日朗瀑布是九寨沟最大的瀑布，气势磅礴。建议秋天去，彩林映衬着碧蓝的湖水，色彩斑斓如油画。门票169元加观光车90元，景区很大，建议坐观光车到最远端再往回走。海拔较高注意高反。',
    tags: ['值得推荐', '水色绝美', '秋季最佳'],
    likes: 134,
    liked: false,
    createdAt: '2025-10-15T10:30:00Z',
  },
  {
    id: 'review-42',
    targetType: 'scenic',
    targetId: 'scenic-sc-2',
    targetName: '都江堰',
    userId: 'user-42',
    userName: '水利工程迷',
    rating: 4,
    content: '都江堰真的是古代工程的奇迹！两千多年前李冰父子设计的水利系统至今仍在运作，灌溉着成都平原。鱼嘴分水堤将岷江分为内外两江，飞沙堰排沙泄洪，宝瓶口引水灌溉，设计之精妙令人叹服。站在安澜索桥上看岷江奔腾而下，感受古人的智慧。门票80元，建议请个讲解员，不然很多水利原理看不懂。可以和青城山安排在同一天，上午都江堰下午青城山。',
    tags: ['值得推荐', '古代奇迹', '建议请讲解'],
    likes: 39,
    liked: false,
    createdAt: '2026-03-12T09:00:00Z',
  },
  {
    id: 'review-43',
    targetType: 'scenic',
    targetId: 'scenic-yn-1',
    targetName: '丽江古城',
    userId: 'user-43',
    userName: '慢生活主义者',
    rating: 4,
    content: '丽江古城的石板路和小桥流水很有韵味，但商业化确实比较严重。四方街周围全是酒吧和纪念品店，有点吵闹。建议往小巷子里走，远离主街后能感受到古城的宁静。木府是古城里最值得看的景点，纳西族土司的宫殿很有特色。束河古镇比大研古镇安静很多，适合发呆喝茶。古城维护费50元，晚上8点后进入免费。建议住古城外的客栈，安静又便宜。',
    tags: ['值得推荐', '适合慢游', '避开主街'],
    likes: 43,
    liked: true,
    createdAt: '2026-02-25T16:00:00Z',
  },
  {
    id: 'review-44',
    targetType: 'scenic',
    targetId: 'scenic-hlj-1',
    targetName: '冰雪大世界',
    userId: 'user-44',
    userName: '冰雪奇缘',
    rating: 5,
    content: '哈尔滨冰雪大世界真的太梦幻了！整座冰雕城堡在彩灯映照下晶莹剔透，仿佛走进了童话世界。冰滑梯是最受欢迎的项目，从几层楼高的冰道上滑下来，又刺激又好玩。建议下午3点左右入园，可以同时看到日景和夜景，天黑后灯光亮起来最漂亮。门票大概300多元，一定要穿最厚的衣服，里面零下二三十度。可以买暖宝宝贴在身上和脚底。手机在低温下会很快关机，记得放在内兜保暖。',
    tags: ['值得推荐', '童话世界', '注意保暖'],
    likes: 76,
    liked: false,
    createdAt: '2026-01-05T15:00:00Z',
  },

  // ---- 行程评价（8条） ----
  {
    id: 'review-45',
    targetType: 'trip',
    targetId: 'trip-sh-1',
    targetName: '上海3日经典游',
    userId: 'user-45',
    userName: '周末出游党',
    rating: 5,
    content: '这个上海三日游行程安排得非常紧凑合理！Day1外滩+南京路+城隍庙，Day2迪士尼全天，Day3武康路+田子坊+新天地。迪士尼建议买早享卡，能多玩两个项目。武康路的武康大楼是网红打卡点，周边有很多精品咖啡馆。新天地晚上去最有氛围，石库门建筑里藏着各种酒吧和餐厅。3天人均2000左右，住宿建议选在人民广场附近，地铁四通八达。',
    tags: ['值得推荐', '安排合理', '适合周末'],
    likes: 55,
    liked: false,
    createdAt: '2026-03-05T18:00:00Z',
  },
  {
    id: 'review-46',
    targetType: 'trip',
    targetId: 'trip-xa-1',
    targetName: '西安4日文化游',
    userId: 'user-46',
    userName: '历史迷老王',
    rating: 5,
    content: '西安四日游太充实了！Day1兵马俑+华清宫，Day2城墙骑行+碑林+回民街，Day3陕西历史博物馆+大雁塔+大唐不夜城，Day4华山一日游。兵马俑一定要请讲解，不然就是看泥人。城墙骑行一圈14公里，大概2小时，傍晚去最舒服。陕西历史博物馆免费但一票难求，建议提前在网上预约。华山建议坐西峰索道上北峰索道下，省体力又能看全景。4天人均2500左右。',
    tags: ['值得推荐', '文化底蕴深厚', '建议请讲解'],
    likes: 68,
    liked: false,
    createdAt: '2026-02-10T20:00:00Z',
  },
  {
    id: 'review-47',
    targetType: 'trip',
    targetId: 'trip-hrb-1',
    targetName: '哈尔滨5日冰雪游',
    userId: 'user-47',
    userName: '南方雪人',
    rating: 4,
    content: '第一次看到这么厚的雪太兴奋了！Day1中央大街+索菲亚教堂，Day2冰雪大世界，Day3亚布力滑雪，Day4雪乡，Day5东北虎林园。冰雪大世界和雪乡是最大的亮点，但真的太冷了，零下30度手机直接冻关机。亚布力滑雪适合新手，教练200块一小时。雪乡的雪蘑菇和木屋很童话，但住宿和餐饮价格偏贵。建议带暖宝宝、保温杯和最厚的羽绒服。5天人均3500左右。',
    tags: ['值得推荐', '注意保暖', '价格偏贵'],
    likes: 42,
    liked: false,
    createdAt: '2026-01-15T14:00:00Z',
  },
  {
    id: 'review-48',
    targetType: 'trip',
    targetId: 'trip-cd-1',
    targetName: '成都4日休闲游',
    userId: 'user-48',
    userName: '巴适得很',
    rating: 5,
    content: '成都真的是一座来了就不想走的城市！Day1大熊猫基地+宽窄巷子，Day2都江堰+青城山，Day3武侯祠+锦里+春熙路，Day4人民公园喝茶+太古里。大熊猫基地建议早上7点半到，能看到熊猫最活跃的吃竹子时间。人民公园的鹤鸣茶社坐一下午，喝盖碗茶掏耳朵，体验最地道的成都慢生活。成都美食太多了，串串、火锅、冒菜、担担面、甜水面...每天吃五顿都不够。4天人均1800，性价比超高。',
    tags: ['值得推荐', '美食天堂', '节奏舒适'],
    likes: 73,
    liked: true,
    createdAt: '2026-03-10T17:00:00Z',
  },
  {
    id: 'review-49',
    targetType: 'trip',
    targetId: 'trip-gz-1',
    targetName: '广州3日美食游',
    userId: 'user-49',
    userName: '食在广州',
    rating: 4,
    content: '广州三日游就是吃吃吃！Day1早茶+沙面+北京路，Day2陈家祠+上下九+珠江夜游，Day3白云山+越秀公园。早茶推荐点都德和陶陶居，虾饺凤爪流沙包必点。沙面的欧式建筑很适合拍照，上下九的步行街虽然老但很有广州味道。珠江夜游建议买尾班船票，夜景更美。白云山可以坐缆车上山，山顶能俯瞰广州全景。3天人均1500，广州的物价对吃货太友好了。唯一不足是天气太热，建议秋冬去。',
    tags: ['值得推荐', '美食集中', '秋冬最佳'],
    likes: 37,
    liked: false,
    createdAt: '2025-11-20T19:00:00Z',
  },
  {
    id: 'review-50',
    targetType: 'trip',
    targetId: 'trip-hz-1',
    targetName: '杭州3日诗意游',
    userId: 'user-50',
    userName: '诗与远方',
    rating: 5,
    content: '杭州三日游太诗意了！Day1西湖环湖+雷峰塔+灵隐寺，Day2西溪湿地+龙井村，Day3宋城+河坊街。西湖建议骑共享单车环湖，断桥、白堤、苏堤、曲院风荷一路骑过去，每个景点都值得停留。灵隐寺的飞来峰石刻很精美，寺内香火旺盛。龙井村可以体验采茶和品茶，龙井虾仁和叫花鸡是必吃的杭帮菜。宋城千古情的演出很震撼，值得一看。3天人均1600，杭州的公共交通很方便。',
    tags: ['值得推荐', '诗意满满', '交通便利'],
    likes: 61,
    liked: false,
    createdAt: '2026-03-18T16:00:00Z',
  },
  {
    id: 'review-51',
    targetType: 'trip',
    targetId: 'trip-yn-1',
    targetName: '云南7日深度游',
    userId: 'user-51',
    userName: '远方旅行者',
    rating: 5,
    content: '云南七日游是我今年最棒的旅行！Day1-2大理古城+洱海环湖+双廊，Day3-4丽江古城+玉龙雪山+蓝月谷，Day5-6香格里拉+普达措+松赞林寺，Day7返程。洱海环湖骑行风景绝美，双廊的海景客栈住一晚看日落太浪漫。玉龙雪山的蓝月谷水色碧蓝如翡翠，比九寨沟也不遑多让。香格里拉的普达措国家公园原始森林和高山湖泊很纯净。7天人均4000，交通费是大头，建议提前订机票和火车票。',
    tags: ['值得推荐', '风景绝美', '建议提前订票'],
    likes: 88,
    liked: false,
    createdAt: '2025-10-01T20:00:00Z',
  },
  {
    id: 'review-52',
    targetType: 'trip',
    targetId: 'trip-cq-1',
    targetName: '重庆3日魔幻游',
    userId: 'user-52',
    userName: '导航废柴',
    rating: 4,
    content: '重庆真的是一座3D魔幻城市！Day1洪崖洞+解放碑+长江索道，Day2磁器口+李子坝轻轨穿楼+涂鸦街，Day3武隆天生三桥一日游。导航在重庆基本没用，因为1楼出去可能是马路，10楼出去也可能是马路。长江索道排队至少1小时，建议工作日去。李子坝看轻轨穿楼确实很神奇，涂鸦街整条街都是涂鸦艺术很出片。武隆天生三桥是变形金刚取景地，天然石桥壮观。重庆火锅每顿都不踩雷，3天人均1500。',
    tags: ['值得推荐', '魔幻3D城市', '火锅天堂'],
    likes: 53,
    liked: false,
    createdAt: '2026-02-15T18:00:00Z',
  },
]
