/**
 * 用户评价 Mock 数据
 * 覆盖 scenic / food / trip 三种类型，内容真实感强
 */
import type { Review } from '@/types'

export const mockReviews: Review[] = [
  // ---- 景点评价 ----
  {
    id: 'review-1',
    targetType: 'scenic',
    targetId: 'scenic-1',
    targetName: '南澳岛',
    userId: 'user-1',
    userName: '海风旅人',
    rating: 5,
    content: '南澳岛真的太美了！环岛公路一路风景如画，青澳湾的沙滩细腻干净，海水清澈见底。日落时分在灯塔旁拍照，随手一拍就是大片。建议租一辆电动车环岛，慢慢逛，每个海湾都值得停下来。岛上物价也很亲民，海鲜大排档新鲜又便宜。',
    tags: ['值得推荐', '风景绝美', '适合拍照'],
    likes: 42,
    liked: false,
    createdAt: '2025-12-15T10:30:00Z',
  },
  {
    id: 'review-2',
    targetType: 'scenic',
    targetId: 'scenic-2',
    targetName: '汕头小公园',
    userId: 'user-2',
    userName: '城市漫步者',
    rating: 4,
    content: '骑楼建筑群很有民国风情，修缮后焕然一新。老妈宫粽球和飘香小吃都在附近，边逛边吃很惬意。不过节假日人太多了，拍照要找角度避开人群。建议工作日去，体验会好很多。晚上灯光亮起来后更有氛围感。',
    tags: ['文化底蕴', '美食集中'],
    likes: 28,
    liked: true,
    createdAt: '2025-12-20T14:20:00Z',
  },
  {
    id: 'review-3',
    targetType: 'scenic',
    targetId: 'scenic-1',
    targetName: '南澳岛',
    userId: 'user-3',
    userName: '背包客小陈',
    rating: 4,
    content: '整体体验不错，但旺季住宿比较紧张，建议提前预订。风很大，记得带件外套。青澳湾适合游泳，后宅湾更适合看日出。岛上交通不太方便，没有公交，要么租车要么包车。海鲜推荐去后宅镇上的大排档，比景区的实惠很多。',
    tags: ['值得推荐', '注意防风'],
    likes: 15,
    liked: false,
    createdAt: '2026-01-05T09:15:00Z',
  },

  // ---- 美食评价 ----
  {
    id: 'review-4',
    targetType: 'food',
    targetId: 'food-1',
    targetName: '牛肉火锅',
    userId: 'user-4',
    userName: '吃货阿杰',
    rating: 5,
    content: '牛肉火锅真的绝了，吊龙入口即化，胸口油脆脆的很有嚼劲，匙柄嫩滑多汁。汤底就是清水加萝卜玉米，完全靠牛肉本身的鲜味。涮的时候师傅会教你每个部位烫几秒，这种仪式感太棒了。人均80左右，性价比超高。强烈推荐吊龙和五花趾！',
    tags: ['值得推荐', '味道惊艳', '性价比高'],
    likes: 67,
    liked: false,
    createdAt: '2025-12-18T20:45:00Z',
  },
  {
    id: 'review-5',
    targetType: 'food',
    targetId: 'food-2',
    targetName: '蚝烙',
    userId: 'user-5',
    userName: '小吃达人',
    rating: 4,
    content: '老妈宫的蚝烙确实名不虚传，外皮酥脆，里面的蚝肉肥美多汁。鱼露的味道很特别，第一次吃可能不太习惯，但配上芫荽就很香。25块钱一份分量很足，两个人吃刚好。建议趁热吃，凉了就不够酥了。',
    tags: ['值得推荐', '地道小吃'],
    likes: 33,
    liked: true,
    createdAt: '2025-12-22T11:30:00Z',
  },
  {
    id: 'review-6',
    targetType: 'food',
    targetId: 'food-3',
    targetName: '夜粥（打冷）',
    userId: 'user-6',
    userName: '深夜觅食者',
    rating: 5,
    content: '打冷绝对是汕头美食的灵魂！上百种冷盘随便挑，卤鹅软烂入味，生腌虾鲜甜弹牙，鱼饭肉质紧实。人均40块就能吃到撑，而且都是新鲜现做的。环境虽然一般，但这就是街头美食的魅力啊。晚上10点后才开始营业，真正的深夜食堂。每次来汕头都要来吃一次。',
    tags: ['值得推荐', '性价比高', '深夜美食'],
    likes: 51,
    liked: false,
    createdAt: '2026-01-02T23:10:00Z',
  },
  {
    id: 'review-7',
    targetType: 'food',
    targetId: 'food-4',
    targetName: '粿条汤',
    userId: 'user-7',
    userName: '早餐爱好者',
    rating: 4,
    content: '飘香小吃店的粿条汤真的很正宗，汤底浓郁鲜甜，粿条滑嫩不糊。牛肉片给得不少，肉丸弹牙有嚼劲。15块钱一碗，在景区附近算很良心了。唯一的缺点是店面太小，高峰期要排队等位。建议早上8点前去，人少不用等。',
    tags: ['值得推荐', '早餐首选'],
    likes: 22,
    liked: false,
    createdAt: '2026-01-08T08:00:00Z',
  },

  // ---- 行程评价 ----
  {
    id: 'review-8',
    targetType: 'trip',
    targetId: 'trip-1',
    targetName: '汕头3日美食之旅',
    userId: 'user-8',
    userName: '旅行规划师',
    rating: 5,
    content: '这个行程安排得太合理了！Day1逛老城区吃小吃，Day2南澳岛环岛，Day3牛肉火锅+特产采购。节奏不紧不慢，每天都能吃到当地特色美食。住宿推荐选在金平区，去哪里都方便。预算控制得很好，3天人均不到1500。强烈推荐给第一次来汕头的朋友！',
    tags: ['值得推荐', '安排合理', '预算友好'],
    likes: 38,
    liked: false,
    createdAt: '2026-01-10T16:30:00Z',
  },
  {
    id: 'review-9',
    targetType: 'trip',
    targetId: 'trip-1',
    targetName: '汕头3日美食之旅',
    userId: 'user-9',
    userName: '周末出游党',
    rating: 4,
    content: '整体行程不错，但Day2南澳岛那天稍微有点赶，建议多留半天时间。跨海大桥收费有点贵，来回100多。岛上租电动车要带驾照，我们没带只能包车，多花了不少钱。不过风景确实很美，美食也都没踩雷。下次来会调整一下节奏，慢慢玩。',
    tags: ['值得推荐', '注意交通'],
    likes: 19,
    liked: true,
    createdAt: '2026-01-12T21:00:00Z',
  },
  {
    id: 'review-10',
    targetType: 'trip',
    targetId: 'trip-2',
    targetName: '潮州文化深度游',
    userId: 'user-10',
    userName: '历史迷小李',
    rating: 5,
    content: '潮州古城真的太有味道了！广济桥的"十八梭船廿四洲"设计绝妙，每天傍晚浮桥断开通航的仪式感满满。牌坊街虽然商业化了一些，但古建筑保存得很好。开元寺很安静，适合慢慢逛。潮州菜比汕头菜更精致，卤鹅和春饼必吃。强烈推荐住一晚古城里的民宿，清晨的古城最美。',
    tags: ['值得推荐', '文化底蕴', '适合慢游'],
    likes: 45,
    liked: false,
    createdAt: '2026-01-15T13:45:00Z',
  },
]
