/**
 * 目的地推荐 Mock 数据
 * 包含 32 个国内热门目的地，每个目的地有完整的评分和标签信息
 * 数据经过真实性校验，评分、预算、季节均参考真实水平
 */
import type { Destination } from '@/types'

export const mockDestinations: Destination[] = [
  {
    id: 'chengdu',
    name: '成都',
    province: '四川',
    coverImage: 'linear-gradient(135deg, #FF6B35, #FFD166)',
    description: '天府之国，一座来了就不想走的城市。这里有悠闲的茶馆文化、热辣的川菜美食、可爱的大熊猫，以及深厚的巴蜀文化底蕴。',
    tags: ['food', 'culture', 'family'],
    bestSeason: '3-6月 / 9-11月',
    avgBudget: 320,
    avgDays: 4,
    rating: 4.7,
    highlights: ['大熊猫繁育研究基地', '宽窄巷子', '锦里古街', '都江堰', '川剧变脸'],
    foodScore: 4.9,
    scenicScore: 4.3,
    cultureScore: 4.6,
    transportScore: 4.5,
    costScore: 4.7,
  },
  {
    id: 'hangzhou',
    name: '杭州',
    province: '浙江',
    coverImage: 'linear-gradient(135deg, #06D6A0, #4ECDC4)',
    description: '人间天堂，西湖美景四季皆宜。龙井茶香弥漫山间，宋韵文化流淌千年，是诗意与自然的完美融合。',
    tags: ['nature', 'culture', 'romantic'],
    bestSeason: '3-5月 / 9-11月',
    avgBudget: 380,
    avgDays: 3,
    rating: 4.6,
    highlights: ['西湖十景', '灵隐寺', '龙井茶园', '西溪湿地', '河坊街'],
    foodScore: 4.3,
    scenicScore: 4.8,
    cultureScore: 4.7,
    transportScore: 4.6,
    costScore: 4.0,
  },
  {
    id: 'dali',
    name: '大理',
    province: '云南',
    coverImage: 'linear-gradient(135deg, #8B5CF6, #EC4899)',
    description: '风花雪月之城，苍山洱海相依相伴。白族古镇韵味悠长，是文艺青年和慢生活爱好者的理想之地。',
    tags: ['nature', 'romantic', 'budget'],
    bestSeason: '3-5月',
    avgBudget: 250,
    avgDays: 4,
    rating: 4.5,
    highlights: ['洱海环湖', '大理古城', '苍山索道', '双廊古镇', '崇圣寺三塔'],
    foodScore: 4.2,
    scenicScore: 4.9,
    cultureScore: 4.4,
    transportScore: 3.8,
    costScore: 4.8,
  },
  {
    id: 'xian',
    name: '西安',
    province: '陕西',
    coverImage: 'linear-gradient(135deg, #F59E0B, #EF476F)',
    description: '十三朝古都，千年历史沉淀。兵马俑震撼世界，古城墙诉说沧桑，回民街美食飘香四溢，大唐不夜城重现盛唐气象。',
    tags: ['culture', 'food', 'family'],
    bestSeason: '3-5月 / 9-11月',
    avgBudget: 300,
    avgDays: 4,
    rating: 4.6,
    highlights: ['秦始皇兵马俑', '古城墙骑行', '回民街', '大唐不夜城', '华清宫'],
    foodScore: 4.6,
    scenicScore: 4.5,
    cultureScore: 5.0,
    transportScore: 4.4,
    costScore: 4.5,
  },
  {
    id: 'xiamen',
    name: '厦门',
    province: '福建',
    coverImage: 'linear-gradient(135deg, #4ECDC4, #44CF6C)',
    description: '海上花园，文艺小资的天堂。鼓浪屿的琴声悠扬，曾厝垵的烟火气十足，环岛路的海风沁人心脾。',
    tags: ['romantic', 'food', 'nature'],
    bestSeason: '3-5月 / 10-12月',
    avgBudget: 350,
    avgDays: 3,
    rating: 4.5,
    highlights: ['鼓浪屿', '南普陀寺', '曾厝垵', '环岛路', '沙坡尾'],
    foodScore: 4.5,
    scenicScore: 4.6,
    cultureScore: 4.2,
    transportScore: 4.3,
    costScore: 4.0,
  },
  {
    id: 'changsha',
    name: '长沙',
    province: '湖南',
    coverImage: 'linear-gradient(135deg, #EF476F, #FF6B35)',
    description: '网红美食之都，夜生活丰富多彩。茶颜悦色、臭豆腐、小龙虾，还有橘子洲头的壮阔湘江，是一座让人来了就不想走的城市。',
    tags: ['food', 'culture', 'budget'],
    bestSeason: '4-6月 / 9-11月',
    avgBudget: 280,
    avgDays: 3,
    rating: 4.4,
    highlights: ['橘子洲头', '岳麓山', '太平老街', '茶颜悦色', '湖南省博物馆'],
    foodScore: 4.8,
    scenicScore: 4.2,
    cultureScore: 4.3,
    transportScore: 4.5,
    costScore: 4.9,
  },
  {
    id: 'chongqing',
    name: '重庆',
    province: '重庆',
    coverImage: 'linear-gradient(135deg, #FF3D00, #FF9100)',
    description: '8D 魔幻城市，山城夜景璀璨夺目。火锅之都麻辣鲜香，洪崖洞的灯火如梦似幻，轻轨穿楼令人惊叹。',
    tags: ['food', 'adventure', 'culture'],
    bestSeason: '3-5月 / 9-11月',
    avgBudget: 280,
    avgDays: 4,
    rating: 4.6,
    highlights: ['洪崖洞', '长江索道', '磁器口古镇', '解放碑', '穿楼轻轨'],
    foodScore: 4.9,
    scenicScore: 4.4,
    cultureScore: 4.3,
    transportScore: 4.0,
    costScore: 4.6,
  },
  {
    id: 'lijiang',
    name: '丽江',
    province: '云南',
    coverImage: 'linear-gradient(135deg, #7C3AED, #2563EB)',
    description: '雪山脚下的浪漫古城，纳西文化神秘悠远。玉龙雪山巍峨壮丽，古城小桥流水别有风情。',
    tags: ['romantic', 'nature', 'culture'],
    bestSeason: '4-5月 / 9-10月',
    avgBudget: 350,
    avgDays: 4,
    rating: 4.4,
    highlights: ['玉龙雪山', '丽江古城', '束河古镇', '蓝月谷', '泸沽湖'],
    foodScore: 4.0,
    scenicScore: 4.8,
    cultureScore: 4.5,
    transportScore: 3.5,
    costScore: 3.8,
  },
  {
    id: 'guilin',
    name: '桂林',
    province: '广西',
    coverImage: 'linear-gradient(135deg, #10B981, #06B6D4)',
    description: '山水甲天下，漓江如诗如画。喀斯特地貌鬼斧神工，阳朔西街热闹非凡，龙脊梯田气势磅礴。',
    tags: ['nature', 'adventure', 'family'],
    bestSeason: '4-10月',
    avgBudget: 300,
    avgDays: 4,
    rating: 4.5,
    highlights: ['漓江竹筏', '阳朔西街', '龙脊梯田', '象鼻山', '遇龙河漂流'],
    foodScore: 4.1,
    scenicScore: 5.0,
    cultureScore: 3.8,
    transportScore: 3.9,
    costScore: 4.4,
  },
  {
    id: 'qingdao',
    name: '青岛',
    province: '山东',
    coverImage: 'linear-gradient(135deg, #0EA5E9, #06D6A0)',
    description: '红瓦绿树，碧海蓝天。啤酒飘香的城市，欧式建筑点缀海岸线，是夏日避暑的绝佳选择。',
    tags: ['nature', 'family', 'food'],
    bestSeason: '6-9月',
    avgBudget: 320,
    avgDays: 3,
    rating: 4.4,
    highlights: ['栈桥', '八大关', '崂山', '青岛啤酒博物馆', '金沙滩'],
    foodScore: 4.3,
    scenicScore: 4.5,
    cultureScore: 4.0,
    transportScore: 4.4,
    costScore: 4.3,
  },
  {
    id: 'suzhou',
    name: '苏州',
    province: '江苏',
    coverImage: 'linear-gradient(135deg, #EC4899, #F59E0B)',
    description: '上有天堂，下有苏杭。精致园林甲天下，昆曲评弹余音绕梁，是江南水乡的极致代表。',
    tags: ['culture', 'romantic', 'luxury'],
    bestSeason: '3-5月 / 9-11月',
    avgBudget: 400,
    avgDays: 3,
    rating: 4.5,
    highlights: ['拙政园', '虎丘', '平江路', '周庄古镇', '苏州博物馆'],
    foodScore: 4.2,
    scenicScore: 4.6,
    cultureScore: 4.9,
    transportScore: 4.7,
    costScore: 3.9,
  },
  {
    id: 'beijing',
    name: '北京',
    province: '北京',
    coverImage: 'linear-gradient(135deg, #DC2626, #F59E0B)',
    description: '千年帝都，现代与传统的完美交融。故宫的恢弘、长城的壮丽、胡同的烟火气，每一处都是中国故事。',
    tags: ['culture', 'family', 'luxury'],
    bestSeason: '4-5月 / 9-10月',
    avgBudget: 500,
    avgDays: 5,
    rating: 4.7,
    highlights: ['故宫博物院', '万里长城（八达岭）', '颐和园', '天坛公园', '南锣鼓巷'],
    foodScore: 4.4,
    scenicScore: 4.7,
    cultureScore: 5.0,
    transportScore: 4.8,
    costScore: 3.5,
  },
  {
    id: 'sanya',
    name: '三亚',
    province: '海南',
    coverImage: 'linear-gradient(135deg, #0EA5E9, #22D3EE)',
    description: '东方夏威夷，碧海蓝天白沙滩。热带风情浓郁，是国内最热门的海滨度假胜地，适合亲子游和情侣度假。',
    tags: ['nature', 'romantic', 'family'],
    bestSeason: '10月-次年3月',
    avgBudget: 450,
    avgDays: 4,
    rating: 4.5,
    highlights: ['亚龙湾', '天涯海角', '蜈支洲岛', '南山文化旅游区', '呀诺达雨林'],
    foodScore: 4.3,
    scenicScore: 4.9,
    cultureScore: 3.5,
    transportScore: 3.8,
    costScore: 3.2,
  },
  {
    id: 'shanghai',
    name: '上海',
    province: '上海',
    coverImage: 'linear-gradient(135deg, #1E3A5F, #E8B86D)',
    description: '东方明珠，国际化大都市的璀璨魅力。外滩万国建筑群与陆家嘴摩天大楼隔江相望，弄堂里藏着最地道的上海味道。',
    tags: ['culture', 'luxury', 'food'],
    bestSeason: '3-5月 / 9-11月',
    avgBudget: 550,
    avgDays: 4,
    rating: 4.6,
    highlights: ['外滩', '东方明珠', '迪士尼乐园', '豫园', '南京路步行街'],
    foodScore: 4.5,
    scenicScore: 4.4,
    cultureScore: 4.7,
    transportScore: 4.9,
    costScore: 3.2,
  },
  {
    id: 'guangzhou',
    name: '广州',
    province: '广东',
    coverImage: 'linear-gradient(135deg, #F97316, #FBBF24)',
    description: '千年商都，食在广州名不虚传。早茶文化源远流长，珠江夜景流光溢彩，岭南建筑独具韵味。',
    tags: ['food', 'culture', 'family'],
    bestSeason: '10月-次年3月',
    avgBudget: 350,
    avgDays: 3,
    rating: 4.4,
    highlights: ['广州塔', '陈家祠', '沙面岛', '白云山', '北京路步行街'],
    foodScore: 4.9,
    scenicScore: 4.2,
    cultureScore: 4.5,
    transportScore: 4.7,
    costScore: 4.2,
  },
  {
    id: 'shenzhen',
    name: '深圳',
    province: '广东',
    coverImage: 'linear-gradient(135deg, #059669, #3B82F6)',
    description: '科技之都，创新之城。从渔村到国际大都市的奇迹，拥有世界级主题公园和绵延的海岸线。',
    tags: ['family', 'luxury', 'adventure'],
    bestSeason: '10月-次年4月',
    avgBudget: 450,
    avgDays: 3,
    rating: 4.3,
    highlights: ['世界之窗', '欢乐谷', '大梅沙海滨公园', '华侨城创意文化园', '深圳湾公园'],
    foodScore: 4.2,
    scenicScore: 4.1,
    cultureScore: 3.8,
    transportScore: 4.8,
    costScore: 3.5,
  },
  {
    id: 'nanjing',
    name: '南京',
    province: '江苏',
    coverImage: 'linear-gradient(135deg, #6366F1, #A78BFA)',
    description: '六朝古都，虎踞龙盘。中山陵庄严肃穆，秦淮河畔灯火阑珊，梧桐大道浪漫迷人，是一座充满历史底蕴的文学之城。',
    tags: ['culture', 'romantic', 'family'],
    bestSeason: '3-5月 / 9-11月',
    avgBudget: 350,
    avgDays: 3,
    rating: 4.5,
    highlights: ['中山陵', '夫子庙秦淮河', '明孝陵', '南京博物院', '玄武湖'],
    foodScore: 4.3,
    scenicScore: 4.4,
    cultureScore: 4.8,
    transportScore: 4.6,
    costScore: 4.1,
  },
  {
    id: 'wuhan',
    name: '武汉',
    province: '湖北',
    coverImage: 'linear-gradient(135deg, #DC2626, #FB923C)',
    description: '九省通衢，江城魅力无限。黄鹤楼千古名篇传颂，热干面过早文化独特，东湖绿道环湖骑行惬意悠然。',
    tags: ['food', 'culture', 'budget'],
    bestSeason: '3-5月 / 9-11月',
    avgBudget: 280,
    avgDays: 3,
    rating: 4.3,
    highlights: ['黄鹤楼', '东湖', '户部巷', '武汉长江大桥', '湖北省博物馆'],
    foodScore: 4.6,
    scenicScore: 4.2,
    cultureScore: 4.4,
    transportScore: 4.5,
    costScore: 4.7,
  },
  {
    id: 'tianjin',
    name: '天津',
    province: '天津',
    coverImage: 'linear-gradient(135deg, #0891B2, #67E8F9)',
    description: '百年租界，万国风情。五大道的洋楼诉说着近代风云，相声茶馆里笑声不断，天津之眼俯瞰海河两岸。',
    tags: ['culture', 'family', 'budget'],
    bestSeason: '4-6月 / 9-11月',
    avgBudget: 280,
    avgDays: 3,
    rating: 4.2,
    highlights: ['五大道', '天津之眼', '古文化街', '意式风情区', '瓷房子'],
    foodScore: 4.4,
    scenicScore: 4.0,
    cultureScore: 4.5,
    transportScore: 4.6,
    costScore: 4.8,
  },
  {
    id: 'haerbin',
    name: '哈尔滨',
    province: '黑龙江',
    coverImage: 'linear-gradient(135deg, #60A5FA, #E0F2FE)',
    description: '冰城哈尔滨，东方莫斯科。冰雪大世界晶莹剔透，中央大街欧式风情浓郁，索菲亚教堂庄严典雅。',
    tags: ['adventure', 'culture', 'romantic'],
    bestSeason: '12月-次年2月',
    avgBudget: 350,
    avgDays: 4,
    rating: 4.5,
    highlights: ['冰雪大世界', '中央大街', '圣索菲亚教堂', '太阳岛', '亚布力滑雪场'],
    foodScore: 4.2,
    scenicScore: 4.7,
    cultureScore: 4.6,
    transportScore: 4.0,
    costScore: 4.2,
  },
  {
    id: 'lasa',
    name: '拉萨',
    province: '西藏',
    coverImage: 'linear-gradient(135deg, #B45309, #FDE68A)',
    description: '日光之城，雪域高原的圣殿。布达拉宫巍峨耸立，大昭寺香火鼎盛，八廓街转经筒声声不息，是无数旅者心中的终极目的地。',
    tags: ['adventure', 'culture', 'nature'],
    bestSeason: '5-10月',
    avgBudget: 500,
    avgDays: 5,
    rating: 4.8,
    highlights: ['布达拉宫', '大昭寺', '八廓街', '纳木错', '色拉寺'],
    foodScore: 3.5,
    scenicScore: 5.0,
    cultureScore: 5.0,
    transportScore: 3.2,
    costScore: 3.0,
  },
  {
    id: 'huhehaote',
    name: '呼和浩特',
    province: '内蒙古',
    coverImage: 'linear-gradient(135deg, #16A34A, #86EFAC)',
    description: '青色之城，草原文化的窗口。大召寺梵音缭绕，蒙古包里奶茶飘香，希拉穆仁草原天高云淡，感受马背上的豪情。',
    tags: ['nature', 'culture', 'adventure'],
    bestSeason: '6-9月',
    avgBudget: 320,
    avgDays: 3,
    rating: 4.1,
    highlights: ['大召寺', '内蒙古博物院', '希拉穆仁草原', '昭君墓', '塞上老街'],
    foodScore: 4.3,
    scenicScore: 4.4,
    cultureScore: 4.3,
    transportScore: 3.8,
    costScore: 4.5,
  },
  {
    id: 'zhangjiajie',
    name: '张家界',
    province: '湖南',
    coverImage: 'linear-gradient(135deg, #15803D, #4ADE80)',
    description: '奇峰三千，秀水八百。石英砂岩峰林地貌举世罕见，阿凡达取景地悬浮山如梦似幻，玻璃栈道惊险刺激。',
    tags: ['nature', 'adventure', 'family'],
    bestSeason: '4-6月 / 9-11月',
    avgBudget: 380,
    avgDays: 4,
    rating: 4.6,
    highlights: ['张家界国家森林公园', '天门山玻璃栈道', '黄龙洞', '宝峰湖', '大峡谷玻璃桥'],
    foodScore: 3.8,
    scenicScore: 5.0,
    cultureScore: 3.5,
    transportScore: 3.5,
    costScore: 3.8,
  },
  {
    id: 'huangshan',
    name: '黄山',
    province: '安徽',
    coverImage: 'linear-gradient(135deg, #78716C, #D6D3D1)',
    description: '五岳归来不看山，黄山归来不看岳。奇松怪石云海温泉四绝闻名天下，徽州古村落粉墙黛瓦如水墨画卷。',
    tags: ['nature', 'culture', 'adventure'],
    bestSeason: '3-5月 / 9-11月',
    avgBudget: 400,
    avgDays: 3,
    rating: 4.7,
    highlights: ['黄山风景区', '宏村', '西递', '屯溪老街', '迎客松'],
    foodScore: 4.0,
    scenicScore: 5.0,
    cultureScore: 4.6,
    transportScore: 3.8,
    costScore: 3.9,
  },
  {
    id: 'jiuzhaigou',
    name: '九寨沟',
    province: '四川',
    coverImage: 'linear-gradient(135deg, #0284C7, #7DD3FC)',
    description: '人间仙境，九寨归来不看水。翠海叠瀑彩林雪峰蓝冰交织成童话世界，是大自然最绚丽的调色盘。',
    tags: ['nature', 'adventure', 'luxury'],
    bestSeason: '9-11月',
    avgBudget: 500,
    avgDays: 4,
    rating: 4.8,
    highlights: ['五花海', '诺日朗瀑布', '珍珠滩瀑布', '长海', '树正群海'],
    foodScore: 3.5,
    scenicScore: 5.0,
    cultureScore: 3.8,
    transportScore: 3.2,
    costScore: 3.0,
  },
  {
    id: 'quanzhou',
    name: '泉州',
    province: '福建',
    coverImage: 'linear-gradient(135deg, #D97706, #FCD34D)',
    description: '半城烟火半城仙，世界遗产之城。开元寺双塔巍然屹立，西街古韵悠长，是海上丝绸之路的起点，多元文化交融之地。',
    tags: ['culture', 'food', 'budget'],
    bestSeason: '10月-次年4月',
    avgBudget: 250,
    avgDays: 3,
    rating: 4.4,
    highlights: ['开元寺', '西街', '清净寺', '洛阳桥', '清源山'],
    foodScore: 4.6,
    scenicScore: 4.2,
    cultureScore: 4.8,
    transportScore: 4.0,
    costScore: 4.8,
  },
  {
    id: 'luoyang',
    name: '洛阳',
    province: '河南',
    coverImage: 'linear-gradient(135deg, #92400E, #F59E0B)',
    description: '十三朝古都，牡丹花都。龙门石窟佛像庄严，白马寺钟声悠远，每年四月牡丹盛开时满城芬芳。',
    tags: ['culture', 'family', 'budget'],
    bestSeason: '4-5月 / 9-10月',
    avgBudget: 260,
    avgDays: 3,
    rating: 4.3,
    highlights: ['龙门石窟', '白马寺', '洛阳博物馆', '老君山', '丽景门'],
    foodScore: 4.3,
    scenicScore: 4.4,
    cultureScore: 4.9,
    transportScore: 4.2,
    costScore: 4.7,
  },
  {
    id: 'kaifeng',
    name: '开封',
    province: '河南',
    coverImage: 'linear-gradient(135deg, #991B1B, #FCA5A5)',
    description: '八朝古都，大宋东京梦华。清明上河园再现千年繁华，开封府包公断案传颂千古，夜市小吃令人流连忘返。',
    tags: ['culture', 'food', 'budget'],
    bestSeason: '4-5月 / 9-10月',
    avgBudget: 220,
    avgDays: 2,
    rating: 4.1,
    highlights: ['清明上河园', '开封府', '大相国寺', '龙亭公园', '鼓楼夜市'],
    foodScore: 4.5,
    scenicScore: 3.8,
    cultureScore: 4.7,
    transportScore: 4.0,
    costScore: 4.9,
  },
  {
    id: 'yangzhou',
    name: '扬州',
    province: '江苏',
    coverImage: 'linear-gradient(135deg, #059669, #A7F3D0)',
    description: '烟花三月下扬州，瘦西湖畔柳如烟。早茶文化精致讲究，园林小巧玲珑别有洞天，是江南最温婉的城市。',
    tags: ['culture', 'romantic', 'food'],
    bestSeason: '3-5月 / 9-11月',
    avgBudget: 300,
    avgDays: 3,
    rating: 4.3,
    highlights: ['瘦西湖', '个园', '何园', '东关街', '大明寺'],
    foodScore: 4.5,
    scenicScore: 4.4,
    cultureScore: 4.6,
    transportScore: 4.2,
    costScore: 4.4,
  },
  {
    id: 'fenghuang',
    name: '凤凰古城',
    province: '湖南',
    coverImage: 'linear-gradient(135deg, #7E22CE, #C084FC)',
    description: '中国最美小城之一，沱江两岸吊脚楼倒映水中。沈从文笔下的边城风情依旧，苗族文化神秘多彩，夜景如诗如画。',
    tags: ['culture', 'romantic', 'budget'],
    bestSeason: '3-5月 / 9-11月',
    avgBudget: 260,
    avgDays: 3,
    rating: 4.3,
    highlights: ['沱江泛舟', '虹桥', '沈从文故居', '古城夜景', '南方长城'],
    foodScore: 4.1,
    scenicScore: 4.5,
    cultureScore: 4.6,
    transportScore: 3.4,
    costScore: 4.7,
  },
  {
    id: 'xishuangbanna',
    name: '西双版纳',
    province: '云南',
    coverImage: 'linear-gradient(135deg, #16A34A, #FDE047)',
    description: '热带雨林秘境，傣族风情浓郁。望天树空中走廊惊险刺激，星光夜市热闹非凡，是冬季避寒的热门选择。',
    tags: ['nature', 'adventure', 'family'],
    bestSeason: '11月-次年4月',
    avgBudget: 350,
    avgDays: 4,
    rating: 4.4,
    highlights: ['中科院热带植物园', '野象谷', '望天树景区', '星光夜市', '傣族园'],
    foodScore: 4.3,
    scenicScore: 4.7,
    cultureScore: 4.3,
    transportScore: 3.5,
    costScore: 4.0,
  },
  {
    id: 'wuyuan',
    name: '婺源',
    province: '江西',
    coverImage: 'linear-gradient(135deg, #EAB308, #FDE68A)',
    description: '中国最美乡村，油菜花海铺满山谷。白墙黛瓦的徽派建筑散落山间，春季金黄花海与秋季红枫构成绝美画卷。',
    tags: ['nature', 'culture', 'romantic'],
    bestSeason: '3-4月 / 11月',
    avgBudget: 280,
    avgDays: 3,
    rating: 4.4,
    highlights: ['篁岭晒秋', '江岭梯田', '月亮湾', '李坑', '彩虹桥'],
    foodScore: 3.9,
    scenicScore: 4.8,
    cultureScore: 4.4,
    transportScore: 3.5,
    costScore: 4.6,
  },
]
